# Generated by Django 6.0.2 on 2026-03-19 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to', models.EmailField(max_length=254, verbose_name='Empfänger')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('html_body', models.TextField(verbose_name='HTML-Inhalt')),
                ('status', models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen'), ('delivered', 'Zugestellt'), ('deferred', 'Verzögert'), ('soft_bounce', 'Soft Bounce'), ('hard_bounce', 'Hard Bounce'), ('blocked', 'Blockiert'), ('invalid', 'Ungültige E-Mail'), ('error', 'Fehler'), ('spam', 'Spam'), ('unsubscribed', 'Abgemeldet'), ('opened', 'Geöffnet'), ('first_open', 'Erstöffnung'), ('clicked', 'Geklickt'), ('proxy_open', 'Proxy-Öffnung'), ('proxy_unique', 'Einmalige Proxy-Öffnung')], default='sent', max_length=20, verbose_name='Status')),
                ('email_trigger', models.CharField(choices=[('automatic', 'Automatisch'), ('manual', 'Manuell')], default='automatic', max_length=20, verbose_name='Typ (automatisch oder manuell)')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Zugestellt am')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Erstmals geöffnet am')),
                ('sent_by', models.CharField(blank=True, max_length=255, verbose_name='Gesendet von')),
                ('matching_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='matching.matchingattempt', verbose_name='Matching')),
                ('request_to_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='matching.requesttocoach', verbose_name='Anfrage an Coach')),
            ],
            options={
                'verbose_name': 'E-Mail-Log',
                'verbose_name_plural': 'E-Mail-Logs',
                'ordering': ['-sent_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('request_to_coach__isnull', True), ('matching_attempt__isnull', True), _connector='OR'), name='emaillog_single_linked_object')],
            },
        ),
    ]
