# Generated by Django 6.0.2 on 2026-03-01 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to', models.EmailField(max_length=254, verbose_name='Empfänger')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('html_body', models.TextField(verbose_name='HTML-Inhalt')),
                ('status', models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen')], default='sent', max_length=10, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='Gesendet von')),
            ],
            options={
                'verbose_name': 'E-Mail-Log',
                'verbose_name_plural': 'E-Mail-Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
