# Generated by Django 6.0.2 on 2026-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
