# Generated by Django 6.0.2 on 2026-03-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_testinvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestInvitation',
        ),
    ]
