# Generated by Django 6.0.2 on 2026-03-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_delete_testinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zugestellt am'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen'), ('delivered', 'Zugestellt'), ('bounced', 'Bounce'), ('spam', 'Spam'), ('blocked', 'Blockiert')], default='sent', max_length=10, verbose_name='Status'),
        ),
    ]
