# Generated by Django 6.0.2 on 2026-03-05 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emaillog_delivered_at_alter_emaillog_status'),
        ('matching', '0002_alter_matchingattempt_options_requesttocoach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='matching_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='matching.matchingattempt', verbose_name='Matching'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='request_to_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='matching.requesttocoach', verbose_name='Anfrage an Coach'),
        ),
        migrations.AddConstraint(
            model_name='emaillog',
            constraint=models.CheckConstraint(condition=models.Q(('request_to_coach__isnull', True), ('matching_attempt__isnull', True), _connector='OR'), name='emaillog_single_linked_object'),
        ),
    ]
