# Generated by Django 6.0.2 on 2026-03-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_emaillog_matching_attempt_emaillog_request_to_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen'), ('delivered', 'Zugestellt'), ('deferred', 'Verzögert'), ('soft_bounce', 'Soft Bounce'), ('hard_bounce', 'Hard Bounce'), ('blocked', 'Blockiert'), ('invalid', 'Ungültige E-Mail'), ('error', 'Fehler'), ('spam', 'Spam'), ('unsubscribed', 'Abgemeldet'), ('opened', 'Geöffnet'), ('first_open', 'Erstöffnung'), ('clicked', 'Geklickt'), ('proxy_open', 'Proxy-Öffnung'), ('proxy_unique', 'Einmalige Proxy-Öffnung')], default='sent', max_length=20, verbose_name='Status'),
        ),
    ]
