# Generated by Django 6.0.2 on 2026-03-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_expand_emaillog_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erstmals geöffnet am'),
        ),
    ]
