# Generated by Django 6.0.2 on 2026-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_add_emaillog_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='sent_by',
            field=models.CharField(blank=True, default='System', max_length=255, verbose_name='Gesendet von'),
            preserve_default=False,
        ),
    ]
