# Generated by Django 6.0.2 on 2026-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_alter_emaillog_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='type',
            field=models.CharField(choices=[('automtic', 'Automatisch'), ('manual', 'Manuell')], default='automtic', max_length=20, verbose_name='Typ (automatisch oder manuell)'),
        ),
    ]
