# Generated by Django 6.0.2 on 2026-03-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_emaillog_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='type',
            new_name='email_trigger',
        ),
    ]
