# Generated by Django 6.0.2 on 2026-03-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_rename_type_emaillog_email_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_trigger',
            field=models.CharField(choices=[('automatic', 'Automatisch'), ('manual', 'Manuell')], default='automatic', max_length=20, verbose_name='Typ (automatisch oder manuell)'),
        ),
    ]
