# Generated by Django 6.0.2 on 2026-03-01 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sprache',
                'verbose_name_plural': 'Sprachen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nachname')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('coaching_format_online', models.BooleanField(default=False, verbose_name='Online')),
                ('coaching_format_presence', models.BooleanField(default=False, verbose_name='Präsenz')),
                ('coaching_format_hybrid', models.BooleanField(default=False, verbose_name='Hybrid')),
                ('status', models.CharField(choices=[('verfuegbar', 'Verfügbar'), ('ausgebucht', 'Ausgebucht'), ('pausiert', 'Pausiert'), ('im_onboarding', 'Im Onboarding'), ('inaktiv', 'Inaktiv')], default='im_onboarding', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, related_name='coaches', to='profiles.language', verbose_name='Sprachen')),
            ],
            options={
                'verbose_name': 'Coach-Profil',
                'verbose_name_plural': 'Coach-Profile',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CoacheeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('coaching_format_online', models.BooleanField(default=False, verbose_name='Online')),
                ('coaching_format_presence', models.BooleanField(default=False, verbose_name='Präsenz')),
                ('coaching_format_hybrid', models.BooleanField(default=False, verbose_name='Hybrid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('languages', models.ManyToManyField(blank=True, related_name='coachees', to='profiles.language', verbose_name='Sprachen')),
            ],
            options={
                'verbose_name': 'Teilnehmer-Profil',
                'verbose_name_plural': 'Teilnehmer-Profile',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
