# Generated by Django 6.0.2 on 2026-03-19 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sprache',
                'verbose_name_plural': 'Sprachen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('bio', models.TextField(blank=True, verbose_name='Biografie')),
                ('coaching_style', models.TextField(blank=True, help_text='Coaching-Stil', verbose_name='Coaching-Stil')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profil')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='coach_photos/', verbose_name='Profilfoto')),
                ('coaching_format_online', models.BooleanField(default=False, verbose_name='Online')),
                ('coaching_format_presence', models.BooleanField(default=False, verbose_name='Präsenz')),
                ('coaching_format_hybrid', models.BooleanField(default=False, verbose_name='Hybrid')),
                ('preferred_communication_channel', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack')], default='slack', max_length=20, verbose_name='Bevorzugter Kommunikationskanal')),
                ('slack_user_id', models.CharField(blank=True, help_text='ID des Slack-Benutzers, z.B. U12345678. Nur erforderlich, wenn der bevorzugte Kommunikationskanal Slack ist.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('paused', 'Pausiert'), ('onboarding', 'Im Onboarding'), ('inactive', 'Inaktiv')], default='onboarding', max_length=20, verbose_name='Status')),
                ('status_notes', models.TextField(blank=True, help_text='Kommentar zum Status', verbose_name='Status-Kommentar')),
                ('maximum_capacity', models.PositiveIntegerField(blank=True, help_text='Maximale Anzahl von Teilnehmer:innen, die gleichzeitig betreut werden können', null=True, verbose_name='Maximale Kapazität')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, related_name='coaches', to='profiles.language', verbose_name='Sprachen')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('coaching_format_online', models.BooleanField(default=False, verbose_name='Online')),
                ('coaching_format_presence', models.BooleanField(default=False, verbose_name='Präsenz')),
                ('coaching_format_hybrid', models.BooleanField(default=False, verbose_name='Hybrid')),
                ('start_date', models.DateField(help_text='Wann soll das Coaching idealerweise starten?', verbose_name='Gewünschtes Startdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background_information', models.TextField(blank=True, verbose_name='Hintergrundinformationen')),
                ('coaching_target', models.TextField(blank=True, verbose_name='Coaching-Ziel')),
                ('avgs_data_docs_available', models.BooleanField(default=False, help_text='Liegen alle notwendigen AVGS-Daten vor, um mit dem Matching zu starten?', verbose_name='AVGS-Daten verfügbar')),
                ('languages', models.ManyToManyField(blank=True, related_name='participants', to='profiles.language', verbose_name='Sprachen')),
            ],
            options={
                'verbose_name': 'Teilnehmer:in',
                'verbose_name_plural': 'Teilnehmer:innen',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
