# Generated by Django 6.0.2 on 2026-03-01 17:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachProfile',
            new_name='Coach',
        ),
        migrations.RenameModel(
            old_name='CoacheeProfile',
            new_name='Participant',
        ),
    ]
