# Generated by Django 6.0.2 on 2026-04-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='city',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='coaching_style',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='profile_photo',
        ),
    ]
