# Generated by Django 6.0.2 on 2026-03-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_coachprofile_coach_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Teilnehmer:in', 'verbose_name_plural': 'Teilnehmer:innen'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='participants', to='profiles.language', verbose_name='Sprachen'),
        ),
    ]
