# Generated by Django 6.0.2 on 2026-04-29 05:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_city_bio_coaching_style_profile_photo_from_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Stadt',
                'verbose_name_plural': 'Städte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Branche',
                'verbose_name_plural': 'Branchen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='coach',
            name='adhs_coaching',
            field=models.BooleanField(default=False, verbose_name='ADHS-Coaching'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coaching_focus',
            field=models.TextField(blank=True, verbose_name='Coaching-Fokus'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coaching_hub_id',
            field=models.UUIDField(blank=True, help_text='Externe UUID aus dem Coaching Hub API.', null=True, unique=True, verbose_name='Coaching Hub ID'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coaching_methods',
            field=models.TextField(blank=True, verbose_name='Coaching-Methoden'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coaching_qualification',
            field=models.TextField(blank=True, verbose_name='Coaching-Qualifikation'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coaching_with_language_barriers',
            field=models.BooleanField(default=False, verbose_name='Sprachbarrieren'),
        ),
        migrations.AddField(
            model_name='coach',
            name='education',
            field=models.TextField(blank=True, verbose_name='Ausbildung'),
        ),
        migrations.AddField(
            model_name='coach',
            name='expert_for_job_applications',
            field=models.BooleanField(default=False, verbose_name='Job-Bewerbungen'),
        ),
        migrations.AddField(
            model_name='coach',
            name='high_profile_coaching',
            field=models.BooleanField(default=False, verbose_name='High-Profile Coaching'),
        ),
        migrations.AddField(
            model_name='coach',
            name='hr_experience',
            field=models.BooleanField(default=False, verbose_name='HR-Erfahrung'),
        ),
        migrations.AddField(
            model_name='coach',
            name='intercultural_coaching',
            field=models.BooleanField(default=False, verbose_name='Interkulturelles Coaching'),
        ),
        migrations.AddField(
            model_name='coach',
            name='leadership_coaching',
            field=models.BooleanField(default=False, verbose_name='Führungscoaching'),
        ),
        migrations.AddField(
            model_name='coach',
            name='lgbtq_coaching',
            field=models.BooleanField(default=False, verbose_name='LGBTQ+ Coaching'),
        ),
        migrations.AddField(
            model_name='coach',
            name='own_coaching_room',
            field=models.BooleanField(default=False, verbose_name='Eigener Coaching-Raum'),
        ),
        migrations.AddField(
            model_name='coach',
            name='preferred_coaching_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bevorzugter Coaching-Ort'),
        ),
        migrations.AddField(
            model_name='coach',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Zusammenfassung'),
        ),
        migrations.AddField(
            model_name='coach',
            name='therapeutic_experience',
            field=models.BooleanField(default=False, verbose_name='Therapeutische Erfahrung'),
        ),
        migrations.AddField(
            model_name='coach',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt aktualisiert (extern)'),
        ),
        migrations.AddField(
            model_name='coach',
            name='work_experience',
            field=models.TextField(blank=True, verbose_name='Berufserfahrung'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coaching_cities',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='profiles.city', verbose_name='Coaching-Städte'),
        ),
        migrations.AddField(
            model_name='coach',
            name='industry_experience',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='profiles.industry', verbose_name='Branchenerfahrung'),
        ),
    ]
