# Generated by Django 6.0.2 on 2026-03-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_beginnerluftstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnerluftstaff',
            name='slack_user_id',
            field=models.CharField(blank=True, help_text='ID des Slack-Benutzers, z.B. U12345678.', max_length=100, null=True),
        ),
    ]
