# Generated by Django 6.0.2 on 2026-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_beginnerluftstaff_slack_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginnerluftstaff',
            name='slack_user_id',
            field=models.CharField(default='XXXXXXXXX', help_text='ID des Slack-Benutzers, z.B. U12345678.', max_length=100),
            preserve_default=False,
        ),
    ]
