# Generated by Django 6.0.2 on 2026-04-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_city_industry_coach_extended_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='coaching_format_hybrid',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='coaching_format_online',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='coaching_format_presence',
        ),
    ]
