# Generated by Django 6.0.2 on 2026-03-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_coach_options_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='last_name',
        ),
    ]
