# Generated by Django 6.0.2 on 2026-04-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_beginnerluftstaff_slack_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='BeginnerLuft Website Profil'),
        ),
    ]
