# Generated by Django 6.0.2 on 2026-03-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_coach_options_remove_coach_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='background_information',
            field=models.TextField(blank=True, verbose_name='Hintergrundinformationen'),
        ),
        migrations.AddField(
            model_name='participant',
            name='coaching_target',
            field=models.TextField(blank=True, verbose_name='Coaching-Ziel'),
        ),
    ]
