# Generated by Django 6.0.2 on 2026-05-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_coaching_format_boolean_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='end_date',
            field=models.DateField(blank=True, help_text='Wann soll das Coaching idealerweise enden?', null=True, verbose_name='Gewünschtes Enddatum'),
        ),
    ]
