# Generated by Django 6.0.2 on 2026-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_participant_background_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='status',
            field=models.CharField(choices=[('verfuegbar', 'Verfügbar'), ('pausiert', 'Pausiert'), ('im_onboarding', 'Im Onboarding'), ('inaktiv', 'Inaktiv')], default='im_onboarding', max_length=20, verbose_name='Status'),
        ),
    ]
