# Generated by Django 6.0.2 on 2026-04-04 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_delete_firsttalk'),
        ('profiles', '0005_coach_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='calendly_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to='bookings.calendlybooking', verbose_name='Calendly-Buchung'),
        ),
    ]
