# Generated by Django 6.0.2 on 2026-05-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_participant_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='avgs_data_docs_available',
            field=models.BooleanField(default=False, help_text='Liegen BeginnerLuft alle notwendigen AVGS-Daten vor, um mit dem Matching zu starten?', verbose_name='AVGS-Daten verfügbar'),
        ),
    ]
