# Generated by Django 6.0.2 on 2026-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_participant_avgs_data_docs_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
    ]
