# Generated by Django 6.0.2 on 2026-03-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_coach_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='status',
            field=models.CharField(choices=[('available', 'Verfügbar'), ('paused', 'Pausiert'), ('onboarding', 'Im Onboarding'), ('inactive', 'Inaktiv')], default='onboarding', max_length=20, verbose_name='Status'),
        ),
    ]
