# Generated by Django 6.0.2 on 2026-03-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_coach_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='preferred_communication_channel',
            field=models.CharField(choices=[('email', 'Email'), ('slack', 'Slack')], default='slack', max_length=20, verbose_name='Bevorzugter Kommunikationskanal'),
        ),
        migrations.AddField(
            model_name='coach',
            name='slack_user_id',
            field=models.CharField(blank=True, help_text='ID des Slack-Benutzers, z.B. U12345678. Nur erforderlich, wenn der bevorzugte Kommunikationskanal Slack ist.', max_length=100, null=True),
        ),
    ]
