# Generated by Django 6.0.2 on 2026-03-14 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_coach_preferred_communication_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Wann soll das Coaching idealerweise starten?', verbose_name='Gewünschtes Startdatum'),
            preserve_default=False,
        ),
    ]
