# Generated by Django 6.0.2 on 2026-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_participant_email_ci_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='start_date',
            field=models.DateField(blank=True, help_text='Wann soll das Coaching idealerweise starten?', null=True, verbose_name='Gewünschtes Startdatum'),
        ),
    ]
