# Generated by Django 6.0.2 on 2026-03-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_participant_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='avgs_data_docs_available',
            field=models.BooleanField(default=False, help_text='Liegen alle notwendigen AVGS-Daten vor, um mit dem Matching zu starten?', verbose_name='AVGS-Daten verfügbar'),
        ),
    ]
