# Generated by Django 6.0.2 on 2026-03-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_participant_avgs_data_docs_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografie'),
        ),
        migrations.AddField(
            model_name='coach',
            name='coaching_style',
            field=models.TextField(blank=True, help_text='Coaching-Stil', verbose_name='Coaching-Stil'),
        ),
        migrations.AddField(
            model_name='coach',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn Profil'),
        ),
        migrations.AddField(
            model_name='coach',
            name='maximum_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximale Anzahl von Teilnehmer:innen, die gleichzeitig betreut werden können', null=True, verbose_name='Maximale Kapazität'),
        ),
        migrations.AddField(
            model_name='coach',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='coach_photos/', verbose_name='Profilfoto'),
        ),
        migrations.AddField(
            model_name='coach',
            name='status_notes',
            field=models.TextField(blank=True, help_text='Kommentar zum Status', verbose_name='Status-Kommentar'),
        ),
    ]
