# Generated by Django 6.0.2 on 2026-05-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='Optionaler Spitzname, mit dem der Chatbot die Person anspricht.', max_length=50, verbose_name='Spitzname'),
        ),
    ]
