# Generated by Django 6.0.2 on 2026-03-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('divers', 'Divers'), ('frau', 'Frau'), ('herr', 'Herr')], help_text='Anrede für den Benutzer (Herr, Frau, Divers). Wichtig, um die Person korrekt ansprechen zu können.', max_length=10, verbose_name='Anrede'),
        ),
    ]
