# Generated by Django 6.0.2 on 2026-03-13 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0050_alter_matchingattempt_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_slack_user_id', models.CharField(max_length=255, verbose_name='Slack User ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('status', models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen')], default='sent', max_length=20, verbose_name='Status')),
                ('slack_trigger', models.CharField(choices=[('automatic', 'Automatisch'), ('manual', 'Manuell')], default='automatic', max_length=20, verbose_name='Typ (automatisch oder manuell)')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
                ('sent_by', models.CharField(blank=True, max_length=255, verbose_name='Gesendet von')),
                ('matching_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_logs', to='matching.matchingattempt', verbose_name='Matching')),
                ('request_to_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_logs', to='matching.requesttocoach', verbose_name='Matching-Anfrage an Coach')),
            ],
            options={
                'verbose_name': 'Slack-Log',
                'verbose_name_plural': 'Slack-Logs',
                'ordering': ['-sent_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('request_to_coach__isnull', True), ('matching_attempt__isnull', True), _connector='OR'), name='slacklog_single_linked_object')],
            },
        ),
    ]
