# Generated by Django 6.0.2 on 2026-04-26 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('message', models.TextField(blank=True, verbose_name='Nachricht')),
                ('blocks', models.JSONField(blank=True, null=True, verbose_name='Slack Blocks')),
                ('status', models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen')], default='sent', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
                ('sent_by', models.CharField(choices=[('System', 'System'), ('Staff', 'Mitarbeiter:in')], default='System', max_length=20, verbose_name='Gesendet von')),
                ('matching_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_logs', to='matching.matchingattempt', verbose_name='Matching')),
                ('request_to_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_logs', to='matching.requesttocoach', verbose_name='Matching-Anfrage an Coach')),
                ('sent_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_slack_logs', to=settings.AUTH_USER_MODEL, verbose_name='Gesendet von (User)')),
                ('to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_slack_logs', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger:in')),
                ('to_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_slack_logs', to='profiles.coach', verbose_name='Empfänger:in (Coach)')),
            ],
            options={
                'verbose_name': 'Slack-Log',
                'verbose_name_plural': 'Slack-Logs',
                'ordering': ['-sent_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('request_to_coach__isnull', False), ('matching_attempt__isnull', False), _negated=True), name='slacklog_at_most_one_linked_object'), models.CheckConstraint(condition=models.Q(models.Q(('sent_by', 'System'), ('sent_by_user__isnull', True)), models.Q(('sent_by', 'Staff'), ('sent_by_user__isnull', False)), _connector='OR'), name='slacklog_sent_by_user_consistency')],
            },
        ),
    ]
