# Generated by Django 6.0.2 on 2026-03-13 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_coach_preferred_communication_channel_and_more'),
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slacklog',
            name='to_slack_user_id',
        ),
        migrations.AddField(
            model_name='slacklog',
            name='to',
            field=models.ForeignKey(default='45b8c76a-a803-494a-b27a-3839839392c4', help_text='An Coach', on_delete=django.db.models.deletion.CASCADE, related_name='slack_logs', to='profiles.coach', verbose_name='Coach'),
            preserve_default=False,
        ),
    ]
