# Generated by Django 6.0.2 on 2026-03-22 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_alter_matchingattempt_state'),
        ('profiles', '0001_initial'),
        ('slack', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slacklog',
            name='slacklog_sent_by_user_consistency',
        ),
        migrations.AddConstraint(
            model_name='slacklog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sent_by', 'System'), ('sent_by_user__isnull', True)), models.Q(('sent_by', 'Staff'), ('sent_by_user__isnull', False)), _connector='OR'), name='slacklog_sent_by_user_consistency'),
        ),
    ]
