# Generated by Django 6.0.2 on 2026-03-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_remove_slacklog_to_slack_user_id_slacklog_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slacklog',
            name='sent_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_slack_logs', to=settings.AUTH_USER_MODEL, verbose_name='Gesendet von'),
        ),
    ]
