# Generated by Django 6.0.2 on 2026-03-22 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_alter_matchingattempt_state'),
        ('profiles', '0001_initial'),
        ('slack', '0002_remove_slacklog_slacklog_sent_by_user_consistency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slacklog',
            name='slacklog_single_linked_object',
        ),
        migrations.AlterField(
            model_name='slacklog',
            name='sent_by',
            field=models.CharField(choices=[('System', 'System'), ('Staff', 'Mitarbeiter:in')], default='System', max_length=20, verbose_name='Gesendet von'),
        ),
        migrations.AlterField(
            model_name='slacklog',
            name='sent_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_slack_logs', to=settings.AUTH_USER_MODEL, verbose_name='Gesendet von (User)'),
        ),
        migrations.AlterField(
            model_name='slacklog',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_logs', to='profiles.coach', verbose_name='Coach'),
        ),
        migrations.AddConstraint(
            model_name='slacklog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('request_to_coach__isnull', False), ('matching_attempt__isnull', True)), models.Q(('request_to_coach__isnull', True), ('matching_attempt__isnull', False)), _connector='OR'), name='slacklog_exactly_one_linked_object'),
        ),
    ]
