# Generated by Django 6.0.2 on 2026-03-22 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_alter_matchingattempt_state'),
        ('profiles', '0001_initial'),
        ('slack', '0003_remove_slacklog_slacklog_single_linked_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slacklog',
            name='slacklog_exactly_one_linked_object',
        ),
        migrations.AddConstraint(
            model_name='slacklog',
            constraint=models.CheckConstraint(condition=models.Q(('request_to_coach__isnull', False), ('matching_attempt__isnull', False), _negated=True), name='slacklog_at_most_one_linked_object'),
        ),
    ]
