# Generated by Django 6.0.2 on 2026-03-13 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0050_alter_matchingattempt_status_and_more'),
        ('profiles', '0008_coach_preferred_communication_channel_and_more'),
        ('slack', '0003_slacklog_sent_by_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slacklog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sent_by', 'system'), ('sent_by_user__isnull', True)), models.Q(('sent_by', 'staff'), ('sent_by_user__isnull', False)), _connector='OR'), name='slacklog_sent_by_user_consistency'),
        ),
    ]
