# Generated by Django 6.0.2 on 2026-03-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_remove_slacklog_slacklog_exactly_one_linked_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slacklog',
            name='slack_trigger',
        ),
    ]
