# Generated by Django 6.0.2 on 2026-03-28 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_remove_slacklog_slack_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='slacklog',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_slack_logs', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger:in'),
        ),
    ]
