# Generated by Django 6.0.2 on 2026-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0006_alter_slacklog_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slacklog',
            name='message',
            field=models.TextField(blank=True, verbose_name='Nachricht'),
        ),
    ]
