"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import dj_database_url
from pathlib import Path
import os

# Load environment variables from a .env file when present (local dev).
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


env_file = os.environ.get("DJANGO_ENV_FILE", ".env.dev")
env_path = BASE_DIR / env_file
if env_path.exists():
    load_dotenv(env_path, override=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("Missing SECRET_KEY environment variable")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')

ENVIRONMENT = os.environ.get("ENVIRONMENT", "development")


ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '127.0.0.1').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://127.0.0.1,http://localhost'
    ).split(',') if o.strip()
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    # Django built-ins
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'anymail',
    'debug_toolbar',
    # Local apps
    'accounts.apps.AccountsConfig',
    'bookings.apps.BookingsConfig',
    'profiles.apps.ProfilesConfig',
    'emails.apps.EmailsConfig',
    'matching.apps.MatchingConfig',
    'slack.apps.SlackConfig',
    'chatbot.apps.ChatbotConfig',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.environment_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    raise ValueError("Missing DATABASE_URL environment variable")

DATABASES = {
    "default": dj_database_url.parse(DATABASE_URL)
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  
STATICFILES_DIRS = [BASE_DIR / 'static']  

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use custom user model (email as username)
AUTH_USER_MODEL = 'accounts.User'

# Authentication redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'

# Email backend — defaults to console in DEBUG mode, Brevo API otherwise.
# Set EMAIL_BACKEND explicitly in .env to override (e.g. to test real sends locally).
_default_email_backend = (
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'anymail.backends.brevo.EmailBackend'
)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', _default_email_backend)

_brevo_api_key = os.environ.get('BREVO_API_KEY', '')
if not DEBUG and not _brevo_api_key:
    raise ValueError('Missing BREVO_API_KEY environment variable')

ANYMAIL = {
    'BREVO_API_KEY': _brevo_api_key,
}

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', '')
# BCC address for every outgoing email — receives a copy in their inbox
EMAIL_BCC = os.environ.get('EMAIL_BCC', '')


# --- Matching / coach request settings ---
# Default number of business hours (weekends skipped) used to pre-fill the
# deadline when a coach invitation is triggered. Staff can override the
# pre-filled value before confirming the send.
COACH_REQUEST_DEFAULT_DEADLINE_HOURS = 24

# Base URL of this site — used to build absolute URLs in emails sent from
# management commands / cron jobs where no HttpRequest is available.
# Must NOT have a trailing slash.
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# Shared secret appended to the Brevo webhook URL as ?secret=<value>.
# Must be set in .env — if missing the endpoint will reject all requests.
BREVO_WEBHOOK_SECRET = os.environ.get('BREVO_WEBHOOK_SECRET', '')

# Calendly webhook signing key — used to verify the HMAC-SHA256 signature on
# every inbound Calendly webhook.
#
# How to set this up:
#   1. Generate a strong random secret (e.g. `python -c "import secrets; print(secrets.token_hex(32))"`)
#   2. Store it in .env as CALENDLY_SIGNING_KEY=<your_secret>
#   3. When registering the webhook subscription via the Calendly API
#      (POST /webhook_subscriptions), pass the same value as the `signing_key`
#      field in the request body.  Calendly will then HMAC-sign every payload
#      it delivers using this key.
#
# Must be set; if missing the endpoint will reject all requests.
CALENDLY_SIGNING_KEY = os.environ.get('CALENDLY_SIGNING_KEY', '')

# Calendly check-in event type URL — used to build the clarification call booking link.
CALENDLY_CHECKIN_URL = os.environ.get('CALENDLY_CHECKIN_URL', 'https://calendly.com/beginnerluft/check-in')

# Brevo webhook IP allowlist. Comma-separated CIDRs.
# Set to empty string in .env to disable the check (local dev / ngrok smoke test).
# Leave unset in .env to enforce Brevo's published ranges in production.
_brevo_ip_ranges_env = os.environ.get('BREVO_WEBHOOK_IP_RANGES', '1.179.112.0/20,172.246.240.0/20')
BREVO_WEBHOOK_IP_RANGES = _brevo_ip_ranges_env if _brevo_ip_ranges_env else None

# Name used for emails generated by the system automatically (e.g. match request notifications to coaches).
SYSTEM_EMAIL_NAME = "Dein BeginnerLuft Team"

# SLACK
SLACK_BOT_TOKEN = os.environ.get('SLACK_BOT_TOKEN', '')
SLACK_SIGNING_SECRET = os.environ.get('SLACK_SIGNING_SECRET', '')

# IONOS AI
IONOS_TOKEN = os.environ.get('IONOS_TOKEN_VALUE', '')
IONOS_BASE_URL = 'https://openai.inference.de-txl.ionos.com/v1'
IONOS_MODEL = 'meta-llama/Llama-3.3-70B-Instruct'

_LOGS_DIR = BASE_DIR / 'logs'
_LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'bookings_file': {
            'class': 'logging.FileHandler',
            'filename': _LOGS_DIR / 'bookings.log',
            'formatter': 'verbose',
            'level': 'INFO',
        },
    },
    'loggers': {
        'matching': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'emails': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'bookings': {
            'handlers': ['console', 'bookings_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
