# Generated by Django 6.0.2 on 2026-03-19 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ue', models.PositiveIntegerField(help_text='Anzahl der genehmigten Unterrichtseinheiten.', verbose_name='Unterrichtseinheiten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('matching_confirmed', 'Matching bestätigt'), ('ready_for_intro_call', 'Bereit für Intro-Call'), ('awaiting_intro_call_feedback', 'Warten auf Intro-Call Rückmeldung'), ('intro_call_confirmed', 'Intro-Call bestätigt'), ('ready_for_start_email', 'Bereit für Start-E-Mail'), ('matching_completed', 'Matching abgeschlossen'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='in_preparation', max_length=50)),
                ('automation_enabled', models.BooleanField(default=False, help_text='Automatisches Versenden von Coach-Anfragen und Erinnerungen.')),
                ('intro_call_requested_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der Coach erstmals gebeten wurde, einen Intro-Call mit dem(r) Teilnehmer:in zu organisieren.', null=True)),
                ('intro_call_confirmed_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der Coach das Intro-Gespräch bestätigt hat.', null=True)),
                ('intro_call_info_sent_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der/die Teilnehmer:in und der Coach Infos für ein Kennenlerngespräch (Intro-Call) erhalten haben.', null=True)),
                ('coaching_start_info_sent_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der/die Teilnehmer:in und der Coach eine Info zum Start des Coachings erhalten haben.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matching_attempts', to=settings.AUTH_USER_MODEL)),
                ('matched_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successful_matches', to='profiles.coach')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_attempts', to='profiles.participant', verbose_name='Teilnehmer:in')),
            ],
            options={
                'verbose_name': 'Matching',
                'verbose_name_plural': 'Matchings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingAttemptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Matching erstellt'), ('started', 'Matching gestartet'), ('automation_enabled', 'Automatisierung aktiviert'), ('automation_disabled', 'Automatisierung deaktiviert'), ('automation_run', 'Automatisierung ausgeführt'), ('coach_request_sent', 'Coach-Anfrage versendet'), ('coach_accepted', 'Coach hat akzeptiert'), ('coach_declined', 'Coach hat abgelehnt'), ('coach_accepted_late', 'Coach hat verspätet akzeptiert'), ('coach_declined_late', 'Coach hat verspätet abgelehnt'), ('coach_response_ignored', 'Coach-Antwort ignoriert'), ('request_deadline_passed', 'Antwortfrist des Coaches abgelaufen'), ('intro_call_requested', 'Intro-Call angefragt'), ('intro_call_confirmed', 'Intro-Call bestätigt'), ('intro_call_declined', 'Intro-Call abgelehnt'), ('intro_call_info_sent', 'Intro-Call Info versendet'), ('coaching_start_info_sent', 'Coaching-Start Info versendet'), ('intro_confirmation_deadline_passed', 'Frist zur Bestätigung des Intro-Calls abgelaufen'), ('intro_call_timeout', 'Intro-Call-Frist überschritten'), ('reminder_sent', 'Erinnerung versendet'), ('manual_override', 'Manuelle Entscheidung durch Mitarbeiter'), ('staff_cancelled_requests', 'Coach-Anfragen durch Mitarbeiter abgebrochen')], max_length=64)),
                ('triggered_by', models.CharField(choices=[('system', 'System'), ('staff', 'BL Mitarbeiter:in'), ('coach', 'Coach')], default='system', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Zusätzliche strukturierte Informationen zum Ereignis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, help_text='Coach, auf den sich das Ereignis bezieht (falls zutreffend)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.coach')),
                ('matching_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matching.matchingattempt')),
                ('triggered_by_user', models.ForeignKey(blank=True, help_text='Benutzer, der das Ereignis ausgelöst hat (nur bei staff oder coach)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ereignis Matching',
                'verbose_name_plural': 'Ereignisse Matching',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingAttemptTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('matching_confirmed', 'Matching bestätigt'), ('ready_for_intro_call', 'Bereit für Intro-Call'), ('awaiting_intro_call_feedback', 'Warten auf Intro-Call Rückmeldung'), ('intro_call_confirmed', 'Intro-Call bestätigt'), ('ready_for_start_email', 'Bereit für Start-E-Mail'), ('matching_completed', 'Matching abgeschlossen'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50)),
                ('to_status', models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('matching_confirmed', 'Matching bestätigt'), ('ready_for_intro_call', 'Bereit für Intro-Call'), ('awaiting_intro_call_feedback', 'Warten auf Intro-Call Rückmeldung'), ('intro_call_confirmed', 'Intro-Call bestätigt'), ('ready_for_start_email', 'Bereit für Start-E-Mail'), ('matching_completed', 'Matching abgeschlossen'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optional explanation for manual or exceptional transitions.')),
                ('matching_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='matching.matchingattempt')),
            ],
            options={
                'verbose_name': 'Status Übergang Matching',
                'verbose_name_plural': 'Status Übergänge Matchings',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestToCoach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveIntegerField(help_text='Kleiner Wert = höhere Priorität.')),
                ('ue', models.PositiveIntegerField(help_text='Anzahl der Unterrichtseinheiten, die der Coach übernehmen soll.', verbose_name='Unterrichtseinheiten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requests_sent', models.PositiveIntegerField(default=0)),
                ('max_number_of_requests', models.PositiveIntegerField(default=3)),
                ('first_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_matching', 'Matching akzeptiert'), ('rejected_matching', 'Matching abgelehnt'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, default='in_preparation', max_length=50)),
                ('deadline_at', models.DateTimeField(blank=True, help_text='Frist für rechtzeitige Antwort', null=True, verbose_name='Antwortfrist')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_requests', to='profiles.coach')),
                ('matching_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_requests', to='matching.matchingattempt')),
            ],
            options={
                'verbose_name': 'Matching-Anfrage an Coach',
                'verbose_name_plural': 'Matching-Anfragen an Coaches',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='CoachActionToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='URL-safe random string generated by secrets.token_urlsafe(48).', max_length=64, unique=True, verbose_name='Token')),
                ('action', models.CharField(choices=[('accept', 'Annehmen'), ('decline', 'Ablehnen'), ('confirm_intro_call', 'Intro-Call bestätigen')], help_text='Baked in at creation — cannot change after the token is issued.', max_length=18, verbose_name='Aktion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('used_at', models.DateTimeField(blank=True, help_text='None = not yet clicked. Set atomically by consume_token() on first use.', null=True, verbose_name='Verwendet am')),
                ('matching_attempt', models.ForeignKey(blank=True, help_text='Das Matching, auf das sich dieser Token bezieht.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_action_tokens', to='matching.matchingattempt', verbose_name='Matching')),
                ('request_to_coach', models.ForeignKey(blank=True, help_text='Die Coach-Anfrage, auf die sich dieser Token bezieht.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_tokens', to='matching.requesttocoach', verbose_name='Anfrage an Coach')),
            ],
            options={
                'verbose_name': 'Coach-Aktions-Token',
                'verbose_name_plural': 'Coach-Aktions-Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestToCoachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Matching-Anfrage erstellt'), ('request_sent', 'Matching-Anfrage gesendet'), ('reminder_sent', 'Reminder gesendet'), ('accepted', 'Matching-Anfrage akzeptiert'), ('rejected', 'Matching-Anfrage abgelehnt'), ('timed_out', 'Deadline überschritten'), ('cancelled', 'Abgebrochen')], db_index=True, max_length=30)),
                ('triggered_by', models.CharField(choices=[('system', 'System'), ('staff', 'BL Mitarbeiter:in'), ('coach', 'Coach')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optionaler Kommentar zum Ereignis')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Zusätzliche strukturierte Informationen (z.B. Reminder-Typ, Deadline, etc.)')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matching.requesttocoach')),
                ('triggered_by_user', models.ForeignKey(blank=True, help_text='Benutzer, der das Ereignis ausgelöst hat (nur bei staff oder coach)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ereignis Matching-Anfrage an Coach',
                'verbose_name_plural': 'Ereignisse Matching-Anfrage an Coaches',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestToCoachTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_matching', 'Matching akzeptiert'), ('rejected_matching', 'Matching abgelehnt'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, max_length=50)),
                ('to_status', models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_matching', 'Matching akzeptiert'), ('rejected_matching', 'Matching abgelehnt'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optionaler Kommentar zur Transition (z.B. Begründung bei manuellen Eingriffen)')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='matching.requesttocoach')),
            ],
            options={
                'verbose_name': 'Status Übergang einer Matching-Anfrage an Coach',
                'verbose_name_plural': 'Status Übergänge der Matching-Anfragen an Coaches',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='matchingattempt',
            index=models.Index(fields=['participant', 'created_at'], name='matching_ma_partici_81358a_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchingattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['in_preparation', 'ready_for_matching', 'matching_ongoing'])), fields=('participant',), name='unique_ongoing_matching_attempt_per_participant'),
        ),
        migrations.AddConstraint(
            model_name='matchingattemptevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('triggered_by', 'system'), ('triggered_by_user__isnull', True)), models.Q(('triggered_by__in', ['staff', 'coach']), ('triggered_by_user__isnull', False)), _connector='OR'), name='matching_attempt_event_valid_triggered_by_user'),
        ),
        migrations.AddIndex(
            model_name='matchingattempttransition',
            index=models.Index(fields=['matching_attempt', 'created_at'], name='matching_ma_matchin_ccfa34_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchingattempttransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='matching_attempt_transition_status_change'),
        ),
        migrations.AddIndex(
            model_name='requesttocoach',
            index=models.Index(fields=['matching_attempt', 'status'], name='matching_re_matchin_758b9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoach',
            constraint=models.UniqueConstraint(fields=('matching_attempt', 'coach'), name='unique_coach_per_matching_attempt'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoach',
            constraint=models.UniqueConstraint(fields=('matching_attempt', 'priority'), name='unique_priority_for_requests_to_coaches'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoach',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'awaiting_reply')), fields=('matching_attempt',), name='one_request_awaiting_reply_per_attempt'),
        ),
        migrations.AddIndex(
            model_name='coachactiontoken',
            index=models.Index(fields=['request_to_coach', 'used_at'], name='matching_co_request_492232_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachactiontoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('request_to_coach__isnull', False), ('matching_attempt__isnull', True)), models.Q(('request_to_coach__isnull', True), ('matching_attempt__isnull', False)), _connector='OR'), name='coach_action_token_linked_to_either_request_or_attempt'),
        ),
        migrations.AddIndex(
            model_name='requesttocoachevent',
            index=models.Index(fields=['request', 'created_at'], name='matching_re_request_511d02_idx'),
        ),
        migrations.AddIndex(
            model_name='requesttocoachevent',
            index=models.Index(fields=['event_type'], name='matching_re_event_t_0ba8f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoachevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('triggered_by', 'system'), ('triggered_by_user__isnull', True)), models.Q(('triggered_by__in', ['staff', 'coach']), ('triggered_by_user__isnull', False)), _connector='OR'), name='rtc_event_valid_triggered_by_user'),
        ),
        migrations.AddIndex(
            model_name='requesttocoachtransition',
            index=models.Index(fields=['request', 'created_at'], name='matching_re_request_7629f6_idx'),
        ),
        migrations.AddIndex(
            model_name='requesttocoachtransition',
            index=models.Index(fields=['from_status'], name='matching_re_from_st_272262_idx'),
        ),
        migrations.AddIndex(
            model_name='requesttocoachtransition',
            index=models.Index(fields=['to_status'], name='matching_re_to_stat_c65e4d_idx'),
        ),
    ]
