# Generated by Django 6.0.2 on 2026-03-04 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_coach_options_alter_participant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_prep', 'In Vorbereitung'), ('awaiting_participant_reply', 'Warten auf TN-Antwort'), ('awaiting_coach_reply', 'Warten auf Coach-Antwort'), ('matched', 'Matched'), ('cancelled', 'Matching abgebrochen')], default='in_prep', max_length=30)),
                ('participant_status', models.CharField(choices=[('accepted', 'Akzeptiert'), ('rejected', 'Abgelehnt'), ('pending', 'Ausstehend')], default='pending', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matching_attempts', to=settings.AUTH_USER_MODEL)),
                ('matched_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_attempts', to='profiles.coach')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_attempts', to='profiles.participant')),
            ],
        ),
    ]
