# Generated by Django 6.0.2 on 2026-03-21 05:38

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ue', models.PositiveIntegerField(help_text='Anzahl der genehmigten Unterrichtseinheiten.', verbose_name='Unterrichtseinheiten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', django_fsm.FSMField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_first_coach_request', 'Bereit für erste Coach-Anfrage'), ('awaiting_rtc_reply', 'Warten auf Coach-Antwort zu Matching-Anfrage'), ('ready_for_intro_call_request', 'Bereit für Intro-Call Anfrage'), ('awaiting_intro_call_reply', 'Warten auf Coach-Antwort zu Intro-Call Anfrage'), ('ready_for_start_notification', 'Bereit für Coaching-Start-Benachrichtigung'), ('matching_completed', 'Matching abgeschlossen'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='in_preparation', max_length=50, protected=True)),
                ('automation_enabled', models.BooleanField(default=False, help_text='Automatisches Versenden von Coach-Anfragen und Erinnerungen.')),
                ('intro_call_requested_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der Coach erstmals gebeten wurde, einen Intro-Call mit dem(r) Teilnehmer:in zu organisieren.', null=True)),
                ('intro_call_confirmed_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der Coach das Intro-Gespräch bestätigt hat.', null=True)),
                ('intro_call_info_sent_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der/die Teilnehmer:in und der Coach Infos für ein Kennenlerngespräch (Intro-Call) erhalten haben.', null=True)),
                ('coaching_start_info_sent_at', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der/die Teilnehmer:in und der Coach eine Info zum Start des Coachings erhalten haben.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matching_attempts', to=settings.AUTH_USER_MODEL)),
                ('matched_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successful_matches', to='profiles.coach')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_attempts', to='profiles.participant', verbose_name='Teilnehmer:in')),
            ],
            options={
                'verbose_name': 'Matching',
                'verbose_name_plural': 'Matchings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestToCoach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveIntegerField(help_text='Kleiner Wert = höhere Priorität.')),
                ('ue', models.PositiveIntegerField(help_text='Anzahl der Unterrichtseinheiten, die der Coach übernehmen soll.', verbose_name='Unterrichtseinheiten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requests_sent', models.PositiveIntegerField(default=0)),
                ('max_number_of_requests', models.PositiveIntegerField(default=3)),
                ('first_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('state', django_fsm.FSMField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted', 'Akzeptiert'), ('rejected', 'Abgelehnt'), ('no_response_until_deadline', 'Keine Rückmeldung bis zur Deadline'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, default='in_preparation', max_length=50, protected=True)),
                ('deadline_at', models.DateTimeField(blank=True, help_text='Frist für rechtzeitige Antwort', null=True, verbose_name='Antwortfrist')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_requests', to='profiles.coach')),
                ('matching_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_requests', to='matching.matchingattempt')),
            ],
            options={
                'verbose_name': 'Matching-Anfrage an Coach',
                'verbose_name_plural': 'Matching-Anfragen an Coaches',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='MatchingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Matching erstellt'), ('started', 'Matching gestartet'), ('completed', 'Matching erfolgreich abgeschlossen'), ('failed', 'Matching fehlgeschlagen / kein Coach gefunden'), ('cancelled', 'Matching abgebrochen'), ('automation_enabled', 'Automatisierung aktiviert'), ('automation_disabled', 'Automatisierung deaktiviert'), ('rtc_created', 'Matching-Anfrage an Coach erstellt'), ('rtc_sent_to_coach', 'Matching-Anfrage an Coach versendet'), ('rtc_reminder_sent_to_coach', 'Erinnerung versendet'), ('rtc_accepted', 'Anfrage akzeptiert'), ('rtc_declined', 'Anfrage abgelehnt'), ('rtc_timed_out', 'Keine Antwort (Timeout)'), ('rtc_cancelled', 'Anfrage abgebrochen'), ('rtc_deleted', 'Matching-Anfrage gelöscht'), ('intro_call_request_sent_to_coach', 'Intro-Call Anfrage an Coach versendet'), ('intro_call_reminder_sent_to_coach', 'Reminder für Intro-Call Anfrage'), ('intro_call_feedback_received_from_coach', 'Feedback vom Coach erhalten'), ('coaching_start_info_sent_to_participant', 'Start-Info an Teilnehmer:in'), ('coaching_start_info_sent_to_coach', 'Start-Info an Coach')], max_length=50)),
                ('triggered_by', models.CharField(choices=[('system', 'System'), ('staff', 'Staff'), ('coach', 'Coach')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Optionales JSON-Feld für zusätzliche Informationen zum Ereignis (z.B. Coach-ID bei RTC-bezogenen Ereignissen)')),
                ('matching_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_events', to='matching.matchingattempt')),
                ('triggered_by_user', models.ForeignKey(blank=True, help_text='Benutzer, der das Ereignis ausgelöst hat (nur bei staff oder coach)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request_to_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matching.requesttocoach')),
            ],
            options={
                'verbose_name': 'Matching Ereignis',
                'verbose_name_plural': 'Matching Ereignisse',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachActionToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='URL-safe random string generated by secrets.token_urlsafe(48).', max_length=64, unique=True, verbose_name='Token')),
                ('action', models.CharField(choices=[('accept', 'Annehmen'), ('decline', 'Ablehnen'), ('confirm_intro_call', 'Intro-Call bestätigen')], help_text='Baked in at creation — cannot change after the token is issued.', max_length=18, verbose_name='Aktion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('used_at', models.DateTimeField(blank=True, help_text='None = not yet clicked. Set atomically by consume_token() on first use.', null=True, verbose_name='Verwendet am')),
                ('matching_attempt', models.ForeignKey(blank=True, help_text='Das Matching, auf das sich dieser Token bezieht.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_action_tokens', to='matching.matchingattempt', verbose_name='Matching')),
                ('request_to_coach', models.ForeignKey(blank=True, help_text='Die Coach-Anfrage, auf die sich dieser Token bezieht.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_tokens', to='matching.requesttocoach', verbose_name='Anfrage an Coach')),
            ],
            options={
                'verbose_name': 'Coach-Aktions-Token',
                'verbose_name_plural': 'Coach-Aktions-Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='matchingattempt',
            index=models.Index(fields=['participant', 'created_at'], name='matching_ma_partici_81358a_idx'),
        ),
        migrations.AddIndex(
            model_name='requesttocoach',
            index=models.Index(fields=['matching_attempt', 'state'], name='matching_re_matchin_0f0f89_idx'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoach',
            constraint=models.UniqueConstraint(fields=('matching_attempt', 'coach'), name='unique_coach_per_matching_attempt'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoach',
            constraint=models.UniqueConstraint(fields=('matching_attempt', 'priority'), name='unique_priority_for_requests_to_coaches'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoach',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'awaiting_reply')), fields=('matching_attempt',), name='one_request_awaiting_reply_per_attempt'),
        ),
        migrations.AddIndex(
            model_name='coachactiontoken',
            index=models.Index(fields=['request_to_coach', 'used_at'], name='matching_co_request_492232_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachactiontoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('request_to_coach__isnull', False), ('matching_attempt__isnull', True)), models.Q(('request_to_coach__isnull', True), ('matching_attempt__isnull', False)), _connector='OR'), name='coach_action_token_linked_to_either_request_or_attempt'),
        ),
    ]
