# Generated by Django 6.0.2 on 2026-03-21 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattempt',
            name='ue',
            field=models.PositiveIntegerField(help_text='Anzahl der genehmigten Unterrichtseinheiten.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unterrichtseinheiten'),
        ),
    ]
