# Generated by Django 6.0.2 on 2026-03-04 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('profiles', '0003_alter_coach_options_alter_participant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchingattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Matching', 'verbose_name_plural': 'Matchings'},
        ),
        migrations.CreateModel(
            name='RequestToCoach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_requests_sent', models.PositiveIntegerField(default=0)),
                ('max_number_of_requests', models.PositiveIntegerField(default=3)),
                ('first_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_on_time', 'Akzeptiert (rechtzeitig)'), ('accepted_late', 'Akzeptiert (verspätet)'), ('rejected_on_time', 'Abgelehnt (rechtzeitig)'), ('rejected_late', 'Abgelehnt (verspätet)'), ('no_response_until_deadline', 'Keine Antwort bis zur Frist'), ('cancelled', 'Anfrage abgebrochen')], default='in_preparation', max_length=50)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_requests', to='profiles.coach')),
                ('last_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_coach_requests', to=settings.AUTH_USER_MODEL)),
                ('matching_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_requests', to='matching.matchingattempt')),
            ],
            options={
                'verbose_name': 'Anfrage an Coach',
                'verbose_name_plural': 'Anfragen an Coaches',
                'ordering': ['-created_at'],
            },
        ),
    ]
