# Generated by Django 6.0.2 on 2026-03-19 05:44

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttocoach',
            name='state',
            field=django_fsm.FSMField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted', 'Akzeptiert'), ('rejected', 'Abgelehnt'), ('no_response_until_deadline', 'Keine Rückmeldung bis zur Deadline'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, default='in_preparation', max_length=50, protected=True),
        ),
    ]
