# Generated by Django 6.0.2 on 2026-03-19 06:05

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_requesttocoach_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingattempt',
            name='state',
            field=django_fsm.FSMField(db_index=True, default='in_preparation', max_length=50, protected=True),
        ),
    ]
