# Generated by Django 6.0.2 on 2026-03-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_matchingattempt_options_requesttocoach'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttocoach',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Frist für rechtzeitige Antwort. Wird beim Versand automatisch vorausgefüllt (Wochenden werden übersprungen), kann aber manuell angepasst werden.', null=True, verbose_name='Antwortfrist'),
        ),
    ]
