# Generated by Django 6.0.2 on 2026-03-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_matchingattempt_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
