# Generated by Django 6.0.2 on 2026-03-07 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_add_deadline_to_request_to_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachActionToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='URL-safe random string generated by secrets.token_urlsafe(48).', max_length=64, unique=True, verbose_name='Token')),
                ('action', models.CharField(choices=[('accept', 'Annehmen'), ('decline', 'Ablehnen')], help_text='Baked in at creation — cannot change after the token is issued.', max_length=10, verbose_name='Aktion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('used_at', models.DateTimeField(blank=True, help_text='None = not yet clicked. Set atomically by consume_token() on first use.', null=True, verbose_name='Verwendet am')),
                ('request_to_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tokens', to='matching.requesttocoach', verbose_name='Anfrage an Coach')),
            ],
            options={
                'verbose_name': 'Coach-Aktions-Token',
                'verbose_name_plural': 'Coach-Aktions-Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
