# Generated by Django 6.0.2 on 2026-03-07 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_add_coach_action_token'),
        ('profiles', '0004_alter_coach_options_remove_coach_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToCoachTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('triggered_by', models.CharField(choices=[('system', 'System'), ('staff', 'BL Mitarbeiter:in'), ('coach', 'Coach')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='requesttocoach',
            name='deadline',
        ),
        migrations.AddField(
            model_name='requesttocoach',
            name='deadline_at',
            field=models.DateTimeField(blank=True, help_text='Frist für rechtzeitige Antwort. Wird beim Versand automatisch vorausgefüllt (Wochenenden werden übersprungen), kann aber manuell angepasst werden.', null=True, verbose_name='Antwortfrist'),
        ),
        migrations.AddField(
            model_name='requesttocoach',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='requesttocoach',
            constraint=models.UniqueConstraint(fields=('matching_attempt', 'coach'), name='unique_coach_request_per_matching_attempt'),
        ),
        migrations.AddField(
            model_name='requesttocoachtransition',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='matching.requesttocoach'),
        ),
    ]
