# Generated by Django 6.0.2 on 2026-03-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_matchingevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchingEvent',
        ),
    ]
