# Generated by Django 6.0.2 on 2026-03-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_requesttocoachtransition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttocoach',
            name='last_sent_by',
        ),
    ]
