# Generated by Django 6.0.2 on 2026-03-19 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_delete_matchingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Matching erstellt'), ('started', 'Matching gestartet'), ('completed', 'Matching erfolgreich abgeschlossen'), ('failed', 'Matching fehlgeschlagen / kein Coach gefunden'), ('cancelled', 'Matching abgebrochen'), ('automation_enabled', 'Automatisierung aktiviert'), ('automation_disabled', 'Automatisierung deaktiviert'), ('rtq_created', 'Matching-Anfrage an Coach erstellt'), ('rtq_sent_to_coach', 'Matching-Anfrage an Coach versendet'), ('rtq_reminder_sent_to_coach', 'Erinnerung versendet'), ('rtq_accepted', 'Anfrage akzeptiert'), ('rtq_declined', 'Anfrage abgelehnt'), ('rtq_timed_out', 'Keine Antwort (Timeout)'), ('rtq_cancelled', 'Anfrage abgebrochen'), ('rtq_deleted', 'Matching-Anfrage gelöscht'), ('intro_call_request_sent_to_coach', 'Intro-Call Anfrage an Coach versendet'), ('intro_call_reminder_sent_to_coach', 'Reminder für Intro-Call Anfrage'), ('intro_call_feedback_received_from_coach', 'Feedback vom Coach erhalten'), ('coaching_start_info_sent_to_participant', 'Start-Info an Teilnehmer:in'), ('coaching_start_info_sent_to_coach', 'Start-Info an Coach')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Optionales JSON-Feld für zusätzliche Informationen zum Ereignis (z.B. Coach-ID bei RTQ-bezogenen Ereignissen)')),
                ('matching_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_events', to='matching.matchingattempt')),
            ],
            options={
                'verbose_name': 'Matching Ereignis',
                'verbose_name_plural': 'Matching Ereignisse',
                'ordering': ['created_at'],
            },
        ),
    ]
