# Generated by Django 6.0.2 on 2026-03-19 07:14

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_matchingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattempt',
            name='state',
            field=django_fsm.FSMField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_first_coach_request', 'Bereit für erste Coach-Anfrage'), ('awaiting_rtc_reply', 'Warten auf Coach-Antwort zu Matching-Anfrage'), ('ready_for_intro_call_request', 'Bereit für Intro-Call Anfrage'), ('awaiting_intro_call_reply', 'Warten auf Coach-Antwort zu Intro-Call Anfrage'), ('ready_for_start_notification', 'Bereit für Coaching-Start-Benachrichtigung'), ('matching_completed', 'Matching abgeschlossen'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='in_preparation', max_length=50, protected=True),
        ),
    ]
