# Generated by Django 6.0.2 on 2026-03-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_remove_requesttocoach_last_sent_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttocoach',
            name='status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_on_time', 'Akzeptiert (rechtzeitig)'), ('accepted_late', 'Akzeptiert (verspätet)'), ('rejected_on_time', 'Abgelehnt (rechtzeitig)'), ('rejected_late', 'Abgelehnt (verspätet)'), ('no_response_until_deadline', 'Keine Antwort bis zur Frist'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, default='in_preparation', max_length=50),
        ),
    ]
