# Generated by Django 6.0.2 on 2026-03-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_alter_requesttocoach_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttocoach',
            old_name='number_of_requests_sent',
            new_name='requests_sent',
        ),
    ]
