# Generated by Django 6.0.2 on 2026-03-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_rename_number_of_requests_sent_requesttocoach_requests_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='from_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_on_time', 'Akzeptiert (rechtzeitig)'), ('accepted_late', 'Akzeptiert (verspätet)'), ('rejected_on_time', 'Abgelehnt (rechtzeitig)'), ('rejected_late', 'Abgelehnt (verspätet)'), ('no_response_until_deadline', 'Keine Antwort bis zur Frist'), ('cancelled', 'Anfrage abgebrochen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='to_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_on_time', 'Akzeptiert (rechtzeitig)'), ('accepted_late', 'Akzeptiert (verspätet)'), ('rejected_on_time', 'Abgelehnt (rechtzeitig)'), ('rejected_late', 'Abgelehnt (verspätet)'), ('no_response_until_deadline', 'Keine Antwort bis zur Frist'), ('cancelled', 'Anfrage abgebrochen')], max_length=50),
        ),
    ]
