# Generated by Django 6.0.2 on 2026-03-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_alter_requesttocoachtransition_from_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToCoachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('request_sent', 'Request sent'), ('reminder_sent', 'Reminder sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=30)),
                ('triggered_by', models.CharField(choices=[('system', 'System'), ('staff', 'BL Mitarbeiter:in'), ('coach', 'Coach')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matching.requesttocoach')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
