# Generated by Django 6.0.2 on 2026-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_requesttocoachevent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coachactiontoken',
            index=models.Index(fields=['request_to_coach', 'used_at'], name='matching_co_request_492232_idx'),
        ),
        migrations.AddIndex(
            model_name='requesttocoachevent',
            index=models.Index(fields=['request', 'created_at'], name='matching_re_request_511d02_idx'),
        ),
    ]
