# Generated by Django 6.0.2 on 2026-03-25 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_alter_matchingevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantActionToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='URL-safe random string generated by secrets.token_urlsafe(48).', max_length=64, unique=True, verbose_name='Token')),
                ('action', models.CharField(choices=[('start_coaching', 'Coaching starten'), ('request_clarification', 'Klärung anfordern')], help_text='Baked in at creation — cannot change after the token is issued.', max_length=30, verbose_name='Aktion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('used_at', models.DateTimeField(blank=True, help_text='None = not yet clicked. Set atomically by consume_token() on first use.', null=True, verbose_name='Verwendet am')),
                ('matching_attempt', models.ForeignKey(blank=True, help_text='Das Matching, auf das sich dieser Token bezieht.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_action_tokens', to='matching.matchingattempt', verbose_name='Matching')),
            ],
            options={
                'verbose_name': 'Teilnehmer-Aktions-Token',
                'verbose_name_plural': 'Teilnehmer-Aktions-Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['matching_attempt', 'used_at'], name='matching_pa_matchin_079b2d_idx')],
            },
        ),
    ]
