# Generated by Django 6.0.2 on 2026-03-08 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_coachactiontoken_matching_co_request_492232_idx_and_more'),
        ('profiles', '0004_alter_coach_options_remove_coach_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingattempt',
            name='participant_status',
        ),
        migrations.AddField(
            model_name='matchingattempt',
            name='automation_enabled',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, werden automatisch Coach-Anfragen verschickt und Erinnerungen gesendet. Kann jederzeit ein- und ausgeschaltet werden.'),
        ),
        migrations.AddField(
            model_name='matchingattempt',
            name='automation_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchingattempt',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchingattempt',
            name='chemistry_confirmation_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchingattempt',
            name='matched_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successful_matches', to='profiles.coach'),
        ),
        migrations.AlterField(
            model_name='matchingattempt',
            name='status',
            field=models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('awaiting_chemistry_confirmation', 'Kennenlerngespräch läuft'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='draft', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='matchingattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'ready_for_matching', 'matching_active', 'awaiting_chemistry_confirmation'])), fields=('participant',), name='unique_active_matching_attempt_per_participant'),
        ),
    ]
