# Generated by Django 6.0.2 on 2026-03-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_participantactiontoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantactiontoken',
            name='action',
            field=models.CharField(choices=[('start_coaching', 'Coaching starten'), ('clarification_needed', 'Klärung benötigt')], help_text='Baked in at creation — cannot change after the token is issued.', max_length=30, verbose_name='Aktion'),
        ),
    ]
