# Generated by Django 6.0.2 on 2026-03-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0012_remove_matchingattempt_participant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttocoach',
            name='priority',
            field=models.PositiveIntegerField(default=10, help_text='Kleiner Wert = höhere Priorität. Bestimmt die Reihenfolge, in der Coaches kontaktiert werden.'),
            preserve_default=False,
        ),
    ]
