# Generated by Django 6.0.2 on 2026-03-25 20:37

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0012_alter_participantactiontoken_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattempt',
            name='state',
            field=django_fsm.FSMField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_rtc_reply', 'Warten auf Coach-Antwort zu Matching-Anfrage'), ('awaiting_intro_call_feedback_from_coach', 'Warten auf Coach-Antwort zu Intro-Call Anfrage'), ('awaiting_intro_call_feedback_from_participant', 'Warten auf Teilnehmer-Antwort zu Intro-Call'), ('clarification_with_participant_needed', 'Klärung mit Teilnehmer:in nötig'), ('ready_for_start_notification', 'Bereit für Coaching-Start-Benachrichtigung'), ('matching_completed', 'Matching abgeschlossen'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='in_preparation', max_length=50, protected=True),
        ),
    ]
