# Generated by Django 6.0.2 on 2026-03-25 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0013_alter_matchingattempt_state'),
        ('profiles', '0002_beginnerluftstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingattempt',
            name='bl_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_attempts', to='profiles.beginnerluftstaff', verbose_name='BL-Kontakt'),
        ),
    ]
