# Generated by Django 6.0.2 on 2026-03-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0013_requesttocoach_priority'),
        ('profiles', '0004_alter_coach_options_remove_coach_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requesttocoach',
            name='unique_coach_request_per_matching_attempt',
        ),
        migrations.AddConstraint(
            model_name='requesttocoach',
            constraint=models.UniqueConstraint(fields=('matching_attempt', 'coach'), name='unique_coach_per_matching_attempt'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoach',
            constraint=models.UniqueConstraint(fields=('matching_attempt', 'priority'), name='unique_priority_for_requests_to_coaches'),
        ),
    ]
