# Generated by Django 6.0.2 on 2026-03-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0014_remove_requesttocoach_unique_coach_request_per_matching_attempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttocoach',
            options={'ordering': ['priority'], 'verbose_name': 'Matching-Anfrage an Coach', 'verbose_name_plural': 'Matching-Anfragen an Coaches'},
        ),
    ]
