# Generated by Django 6.0.2 on 2026-03-08 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0015_alter_requesttocoach_options'),
        ('profiles', '0004_alter_coach_options_remove_coach_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingAttemptTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('awaiting_chemistry_confirmation', 'Kennenlerngespräch läuft'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50)),
                ('to_status', models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('awaiting_chemistry_confirmation', 'Kennenlerngespräch läuft'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50)),
                ('triggered_by', models.CharField(choices=[('system', 'System'), ('staff', 'BL Mitarbeiter:in'), ('coach', 'Coach')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='requesttocoach',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'awaiting_reply')), fields=('matching_attempt',), name='one_request_awaiting_reply_per_attempt'),
        ),
        migrations.AddField(
            model_name='matchingattempttransition',
            name='matching_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='matching.matchingattempt'),
        ),
        migrations.AddField(
            model_name='matchingattempttransition',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
