# Generated by Django 6.0.2 on 2026-03-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0016_alter_matchingevent_triggered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Matching erstellt'), ('started', 'Matching gestartet'), ('completed', 'Matching erfolgreich abgeschlossen'), ('failed', 'Matching fehlgeschlagen / kein Coach gefunden'), ('cancelled', 'Matching abgebrochen'), ('automation_enabled', 'Automatisierung aktiviert'), ('automation_disabled', 'Automatisierung deaktiviert'), ('rtc_created', 'Matching-Anfrage an Coach erstellt'), ('rtc_sent_to_coach', 'Matching-Anfrage an Coach versendet'), ('rtc_reminder_sent_to_coach', 'Erinnerung versendet'), ('rtc_accepted', 'Matching-Anfrage akzeptiert'), ('rtc_declined', 'Matching-Anfrage abgelehnt'), ('rtc_timed_out', 'Keine Antwort (Timeout)'), ('rtc_cancelled', 'Matching-Anfrage abgebrochen'), ('rtc_deleted', 'Matching-Anfrage gelöscht'), ('intro_call_request_sent_to_coach', 'Intro-Call Anfrage an Coach versendet'), ('intro_call_reminder_sent_to_coach', 'Reminder für Intro-Call Anfrage'), ('intro_call_feedback_received_from_coach', 'Feedback zum Intro-Call von Coach erhalten'), ('intro_call_info_sent_to_participant', 'Intro-Call Informationen an Teilnehmer:in versendet'), ('intro_call_feedback_requested_from_participant', 'Feedback zum Intro-Call bei Teilnehmer:in angefragt'), ('coaching_can_start_feedback_received_from_participant', 'Feedback zum Intro-Call von Teilnehmer:in erhalten'), ('clarification_needed_feedback_received_from_participant', 'Teilnehmer:in hat um Klärung gebeten'), ('escalation_notification_sent_to_staff', 'Benachrichtigung an BL über notwendige Klärung gesendet'), ('information_about_clarification_sent_to_coach', 'Coach über notwendige Klärung informiert'), ('coaching_start_info_sent_to_participant', 'Start-Info an Teilnehmer:in versendet'), ('coaching_start_info_sent_to_coach', 'Start-Info an Coach versendet')], max_length=100),
        ),
    ]
