# Generated by Django 6.0.2 on 2026-03-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0017_alter_matchingevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingevent',
            name='triggered_by',
            field=models.CharField(choices=[('system', 'System'), ('staff', 'BL'), ('coach', 'Coach'), ('participant', 'Teilnehmer:in')], default='system', max_length=20),
        ),
    ]
