# Generated by Django 6.0.2 on 2026-03-08 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0017_requesttocoachtransition_triggered_by_user'),
        ('profiles', '0004_alter_coach_options_remove_coach_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matchingattempt',
            index=models.Index(fields=['participant', 'created_at'], name='matching_ma_partici_81358a_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingattempttransition',
            index=models.Index(fields=['matching_attempt', 'created_at'], name='matching_ma_matchin_ccfa34_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchingattempttransition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('triggered_by', 'system'), ('triggered_by_user__isnull', True)), models.Q(('triggered_by__in', ['staff', 'coach']), ('triggered_by_user__isnull', False)), _connector='OR'), name='transition_actor_consistency'),
        ),
    ]
