# Generated by Django 6.0.2 on 2026-03-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0018_matchingattempt_matching_ma_partici_81358a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttocoachevent',
            name='event_type',
            field=models.CharField(choices=[('request_sent', 'Request sent'), ('reminder_sent', 'Reminder sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('timed_out', 'Deadline passed'), ('cancelled', 'Cancelled')], max_length=30),
        ),
    ]
