# Generated by Django 6.0.2 on 2026-03-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0019_alter_requesttocoachevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttocoachevent',
            name='event_type',
            field=models.CharField(choices=[('request_sent', 'Matching-Anfrage gesendet'), ('reminder_sent', 'Reminder gesendet'), ('accepted', 'Matching-Anfrage akzeptiert'), ('rejected', 'Matching-Anfrage abgelehnt'), ('timed_out', 'Deadline überschritten'), ('cancelled', 'Abgebrochen')], max_length=30),
        ),
    ]
