# Generated by Django 6.0.2 on 2026-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0020_alter_requesttocoachevent_event_type'),
        ('profiles', '0004_alter_coach_options_remove_coach_first_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='requesttocoach',
            index=models.Index(fields=['matching_attempt', 'status'], name='matching_re_matchin_758b9d_idx'),
        ),
    ]
