# Generated by Django 6.0.2 on 2026-03-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0021_requesttocoach_matching_re_matchin_758b9d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttocoach',
            name='status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_on_time', 'Akzeptiert (rechtzeitig)'), ('accepted_late', 'Akzeptiert (verspätet)'), ('rejected_on_time', 'Abgelehnt (rechtzeitig)'), ('rejected_late', 'Abgelehnt (verspätet)'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, default='in_preparation', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='from_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_on_time', 'Akzeptiert (rechtzeitig)'), ('accepted_late', 'Akzeptiert (verspätet)'), ('rejected_on_time', 'Abgelehnt (rechtzeitig)'), ('rejected_late', 'Abgelehnt (verspätet)'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='to_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_on_time', 'Akzeptiert (rechtzeitig)'), ('accepted_late', 'Akzeptiert (verspätet)'), ('rejected_on_time', 'Abgelehnt (rechtzeitig)'), ('rejected_late', 'Abgelehnt (verspätet)'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], max_length=50),
        ),
    ]
