# Generated by Django 6.0.2 on 2026-03-09 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0022_alter_requesttocoach_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingAttemptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('matching_started', 'Matching gestartet'), ('automation_enabled', 'Auto E-Mails aktiviert'), ('automation_disabled', 'Auto E-Mails deaktiviert'), ('matching_cancelled', 'Matching abgebrochen'), ('request_sent', 'Matching-Anfrage gesendet'), ('reminder_sent', 'Reminder gesendet'), ('rtc_cancelled', 'Anfrage an Coach abgebrochen'), ('rtc_timed_out', 'Deadline überschritten'), ('rtc_accepted', 'Matching-Anfrage akzeptiert'), ('rtc_rejected', 'Matching-Anfrage abgelehnt')], max_length=30)),
                ('triggered_by', models.CharField(choices=[('system', 'System'), ('staff', 'BL Mitarbeiter:in'), ('coach', 'Coach')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('matching_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matching.matchingattempt')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['matching_attempt', 'created_at'], name='matching_ma_matchin_c6b828_idx')],
            },
        ),
    ]
