# Generated by Django 6.0.2 on 2026-03-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0023_matchingattemptevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattempt',
            name='status',
            field=models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('rtc_accepted', 'Erstanfrage von Coach akzeptiert'), ('awaiting_chemistry_confirmation', 'Kennenlerngespräch läuft'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattemptevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Matching erstellt'), ('matching_started', 'Matching gestartet'), ('automation_enabled', 'Auto E-Mails aktiviert'), ('automation_disabled', 'Auto E-Mails deaktiviert'), ('matching_cancelled', 'Matching abgebrochen'), ('request_sent', 'Matching-Anfrage gesendet'), ('reminder_sent', 'Reminder gesendet'), ('rtc_cancelled', 'Anfrage an Coach abgebrochen'), ('rtc_timed_out', 'Deadline überschritten'), ('rtc_accepted', 'Matching-Anfrage akzeptiert'), ('rtc_rejected', 'Matching-Anfrage abgelehnt')], max_length=30),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='from_status',
            field=models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('rtc_accepted', 'Erstanfrage von Coach akzeptiert'), ('awaiting_chemistry_confirmation', 'Kennenlerngespräch läuft'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='to_status',
            field=models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('rtc_accepted', 'Erstanfrage von Coach akzeptiert'), ('awaiting_chemistry_confirmation', 'Kennenlerngespräch läuft'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
    ]
