# Generated by Django 6.0.2 on 2026-03-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0024_alter_matchingattempt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattemptevent',
            name='triggered_by',
            field=models.CharField(choices=[('system', 'System'), ('staff', 'BL Mitarbeiter:in'), ('coach', 'Coach')], max_length=30),
        ),
    ]
