# Generated by Django 6.0.2 on 2026-03-09 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0025_alter_matchingattemptevent_triggered_by'),
        ('profiles', '0004_alter_coach_options_remove_coach_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchingattempt',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='matchingattempt',
            name='unique_active_matching_attempt_per_participant',
        ),
        migrations.RenameField(
            model_name='matchingattempt',
            old_name='chemistry_confirmation_received_at',
            new_name='chemistry_confirmed_at',
        ),
        migrations.AddField(
            model_name='matchingattempt',
            name='chemistry_deadline_at',
            field=models.DateTimeField(blank=True, help_text='Deadline by which the coach must confirm the chemistry call.', null=True),
        ),
        migrations.AddField(
            model_name='matchingattempt',
            name='chemistry_declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchingattempt',
            name='chemistry_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchingattempt',
            name='automation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchingattempt',
            name='status',
            field=models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('chemistry_pending', 'Kennenlerngespräch ausstehend'), ('chemistry_timeout', 'Kennenlerngespräch nicht bestätigt'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='from_status',
            field=models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('chemistry_pending', 'Kennenlerngespräch ausstehend'), ('chemistry_timeout', 'Kennenlerngespräch nicht bestätigt'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='to_status',
            field=models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('chemistry_pending', 'Kennenlerngespräch ausstehend'), ('chemistry_timeout', 'Kennenlerngespräch nicht bestätigt'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='matchingattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'ready_for_matching', 'matching_active', 'chemistry_pending'])), fields=('participant',), name='unique_active_matching_attempt_per_participant'),
        ),
    ]
