# Generated by Django 6.0.2 on 2026-03-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0026_alter_matchingattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattempt',
            name='automation_enabled',
            field=models.BooleanField(default=False, help_text='Automatisches Versenden von Coach-Anfragen und Erinnerungen.'),
        ),
        migrations.AlterField(
            model_name='matchingattempt',
            name='chemistry_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchingattempt',
            name='status',
            field=models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('chemistry_pending', 'Kennenlerngespräch läuft'), ('chemistry_timeout', 'Kennenlerngespräch nicht bestätigt'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='from_status',
            field=models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('chemistry_pending', 'Kennenlerngespräch läuft'), ('chemistry_timeout', 'Kennenlerngespräch nicht bestätigt'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='to_status',
            field=models.CharField(choices=[('draft', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_active', 'Matching läuft'), ('chemistry_pending', 'Kennenlerngespräch läuft'), ('chemistry_timeout', 'Kennenlerngespräch nicht bestätigt'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
    ]
