# Generated by Django 6.0.2 on 2026-03-09 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0027_alter_matchingattempt_automation_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchingattempttransition',
            name='transition_actor_consistency',
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='note',
            field=models.TextField(blank=True, help_text='Optional explanation for manual or exceptional transitions.'),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, help_text="Required if triggered_by is 'staff' or 'coach'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='matchingattempttransition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('triggered_by', 'system'), ('triggered_by_user__isnull', True)), models.Q(('triggered_by__in', ['staff', 'coach']), ('triggered_by_user__isnull', False)), _connector='OR'), name='matching_attempt_transition_actor_consistency'),
        ),
        migrations.AddConstraint(
            model_name='matchingattempttransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='matching_attempt_transition_status_change'),
        ),
    ]
