# Generated by Django 6.0.2 on 2026-04-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0027_alter_matchingevent_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttocoach',
            name='first_sent_at',
        ),
        migrations.RemoveField(
            model_name='requesttocoach',
            name='last_sent_at',
        ),
        migrations.RemoveField(
            model_name='requesttocoach',
            name='requests_sent',
        ),
    ]
