# Generated by Django 6.0.2 on 2026-03-09 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0028_remove_matchingattempttransition_transition_actor_consistency_and_more'),
        ('profiles', '0004_alter_coach_options_remove_coach_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchingattemptevent',
            name='matching_ma_matchin_c6b828_idx',
        ),
        migrations.AddField(
            model_name='matchingattemptevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who triggered the event (coach, staff, system)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchingattemptevent',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.coach'),
        ),
        migrations.AddField(
            model_name='matchingattemptevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra structured data (deadline, email id, etc.)'),
        ),
        migrations.AlterField(
            model_name='matchingattemptevent',
            name='event_type',
            field=models.CharField(choices=[('coach_request_sent', 'Coach Request Sent'), ('coach_accepted', 'Coach Accepted'), ('coach_declined', 'Coach Declined'), ('coach_accepted_late', 'Coach Accepted Late'), ('coach_declined_late', 'Coach Declined Late'), ('coach_response_ignored', 'Coach Response Ignored'), ('request_deadline_passed', 'Request Deadline Passed'), ('chemistry_confirmation_deadline_passed', 'Chemistry Confirmation Deadline Passed'), ('chemistry_call_requested', 'Chemistry Call Requested'), ('chemistry_call_confirmed', 'Chemistry Call Confirmed'), ('chemistry_call_declined', 'Chemistry Call Declined'), ('chemistry_call_timeout', 'Chemistry Call Timeout'), ('reminder_sent', 'Reminder Sent'), ('manual_override', 'Manual Override'), ('staff_cancelled_requests', 'Staff Cancelled Requests')], max_length=64),
        ),
        migrations.RemoveField(
            model_name='matchingattemptevent',
            name='note',
        ),
        migrations.RemoveField(
            model_name='matchingattemptevent',
            name='triggered_by',
        ),
    ]
