# Generated by Django 6.0.2 on 2026-04-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0028_remove_vestigial_rtc_tracking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttocoach',
            name='max_number_of_requests',
        ),
    ]
