# Generated by Django 6.0.2 on 2026-03-09 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0029_remove_matchingattemptevent_matching_ma_matchin_c6b828_idx_and_more'),
        ('profiles', '0004_alter_coach_options_remove_coach_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattemptevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Benutzer, der das Ereignis ausgelöst hat (Coach, Mitarbeiter oder System)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchingattemptevent',
            name='coach',
            field=models.ForeignKey(blank=True, help_text='Coach, auf den sich das Ereignis bezieht (falls zutreffend)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.coach'),
        ),
        migrations.AlterField(
            model_name='matchingattemptevent',
            name='event_type',
            field=models.CharField(choices=[('automation_enabled', 'Automatisierung aktiviert'), ('automation_disabled', 'Automatisierung deaktiviert'), ('automation_run', 'Automatisierung ausgeführt'), ('coach_request_sent', 'Coach-Anfrage versendet'), ('coach_accepted', 'Coach hat akzeptiert'), ('coach_declined', 'Coach hat abgelehnt'), ('coach_accepted_late', 'Coach hat verspätet akzeptiert'), ('coach_declined_late', 'Coach hat verspätet abgelehnt'), ('coach_response_ignored', 'Coach-Antwort ignoriert'), ('request_deadline_passed', 'Antwortfrist des Coaches abgelaufen'), ('chemistry_call_requested', 'Chemiegespräch angefragt'), ('chemistry_call_confirmed', 'Chemiegespräch bestätigt'), ('chemistry_call_declined', 'Chemiegespräch abgelehnt'), ('chemistry_confirmation_deadline_passed', 'Frist zur Bestätigung des Chemiegesprächs abgelaufen'), ('chemistry_call_timeout', 'Chemiegespräch-Frist überschritten'), ('reminder_sent', 'Erinnerung versendet'), ('manual_override', 'Manuelle Entscheidung durch Mitarbeiter'), ('staff_cancelled_requests', 'Coach-Anfragen durch Mitarbeiter abgebrochen')], max_length=64),
        ),
        migrations.AlterField(
            model_name='matchingattemptevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Zusätzliche strukturierte Informationen zum Ereignis'),
        ),
    ]
