# Generated by Django 6.0.2 on 2026-03-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0030_alter_matchingattemptevent_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttocoach',
            name='deadline_at',
            field=models.DateTimeField(blank=True, help_text='Frist für rechtzeitige Antwort', null=True, verbose_name='Antwortfrist'),
        ),
        migrations.AlterField(
            model_name='requesttocoach',
            name='priority',
            field=models.PositiveIntegerField(help_text='Kleiner Wert = höhere Priorität.'),
        ),
    ]
