# Generated by Django 6.0.2 on 2026-04-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0030_remove_ready_for_start_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingattempt',
            name='intro_call_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='matchingattempt',
            name='intro_call_info_sent_at',
        ),
        migrations.RemoveField(
            model_name='matchingattempt',
            name='intro_call_requested_at',
        ),
    ]
