# Generated by Django 6.0.2 on 2026-03-09 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0031_alter_requesttocoach_deadline_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='from_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_on_time', 'Akzeptiert (rechtzeitig)'), ('accepted_late', 'Akzeptiert (verspätet)'), ('rejected_on_time', 'Abgelehnt (rechtzeitig)'), ('rejected_late', 'Abgelehnt (verspätet)'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='note',
            field=models.TextField(blank=True, help_text='Optionaler Kommentar zur Transition (z.B. Begründung bei manuellen Eingriffen)'),
        ),
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='to_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_on_time', 'Akzeptiert (rechtzeitig)'), ('accepted_late', 'Akzeptiert (verspätet)'), ('rejected_on_time', 'Abgelehnt (rechtzeitig)'), ('rejected_late', 'Abgelehnt (verspätet)'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, help_text='Benutzer, der die Transition ausgelöst hat (nur bei staff oder coach)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='requesttocoachtransition',
            index=models.Index(fields=['request', 'created_at'], name='matching_re_request_7629f6_idx'),
        ),
        migrations.AddIndex(
            model_name='requesttocoachtransition',
            index=models.Index(fields=['from_status'], name='matching_re_from_st_272262_idx'),
        ),
        migrations.AddIndex(
            model_name='requesttocoachtransition',
            index=models.Index(fields=['to_status'], name='matching_re_to_stat_c65e4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoachtransition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('triggered_by', 'system'), ('triggered_by_user__isnull', True)), models.Q(('triggered_by__in', ['staff', 'coach']), ('triggered_by_user__isnull', False)), _connector='OR'), name='rtc_transition_valid_triggered_by_user'),
        ),
    ]
