# Generated by Django 6.0.2 on 2026-04-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0031_remove_legacy_intro_call_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingattempt',
            name='intro_call_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Frist, bis zu der der Coach einen Intro-Call mit dem(r) Teilnehmer:in organisieren soll.', null=True, verbose_name='Frist für Intro-Call'),
        ),
    ]
