# Generated by Django 6.0.2 on 2026-04-19 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0032_add_intro_call_deadline_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Matching erstellt'), ('started', 'Matching gestartet'), ('resumed', 'Matching fortgesetzt'), ('completed', 'Matching erfolgreich abgeschlossen'), ('failed', 'Matching fehlgeschlagen / kein Coach gefunden'), ('cancelled', 'Matching abgebrochen'), ('automation_enabled', 'Automatisierung aktiviert'), ('automation_disabled', 'Automatisierung deaktiviert'), ('rtc_created', 'Matching-Anfrage an Coach erstellt'), ('rtc_sent_to_coach', 'Matching-Anfrage an Coach versendet'), ('rtc_reminder_sent_to_coach', 'Erinnerung versendet'), ('rtc_accepted', 'Matching-Anfrage akzeptiert'), ('rtc_declined', 'Matching-Anfrage abgelehnt'), ('rtc_timed_out', 'Keine Antwort (Timeout)'), ('rtc_cancelled', 'Matching-Anfrage abgebrochen'), ('responded_late_to_rtc', 'Antwort nach Deadline'), ('rtc_deleted', 'Matching-Anfrage gelöscht'), ('all_rtcs_declined', 'Alle Matching-Anfragen abgelehnt'), ('intro_call_request_sent_to_coach', 'Intro-Call Anfrage an Coach versendet'), ('intro_call_reminder_sent_to_coach', 'Reminder für Intro-Call Anfrage'), ('intro_call_timed_out_staff_notified', 'Staff über abgelaufene Intro-Call Frist informiert'), ('intro_call_feedback_received_from_coach', 'Feedback zum Intro-Call von Coach erhalten'), ('intro_call_info_sent_to_participant', 'Intro-Call Informationen an TN versendet'), ('intro_call_feedback_requested_from_participant', 'Feedback zum Intro-Call bei TN angefragt'), ('coaching_can_start_feedback_received_from_participant', 'Positives Feedback zum Intro-Call von TN erhalten'), ('clarification_needed_feedback_received_from_participant', 'TN hat nach Intro-Call um Klärung gebeten'), ('escalation_notification_sent_to_staff', 'BeginnerLuft über notwendige Klärung informiert'), ('information_about_clarification_sent_to_coach', 'Coach über notwendige Klärung informiert'), ('clarification_call_booked', 'TN hat Klärungsgespräch gebucht (Calendly)'), ('clarification_call_canceled', 'TN hat Klärungsgespräch abgesagt (Calendly)'), ('coaching_start_info_sent_to_participant', 'Start-Info an TN versendet'), ('coaching_start_info_sent_to_coach', 'Start-Info an Coach versendet'), ('manually_matched_to_coach', 'Manuell mit Coach gematcht')], max_length=100),
        ),
        migrations.CreateModel(
            name='ClarificationCallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendly_event_uri', models.URLField(blank=True)),
                ('calendly_invitee_uri', models.URLField(blank=True, unique=True)),
                ('invitee_email', models.EmailField(blank=True, max_length=254)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('clarification_category', models.CharField(blank=True, max_length=255)),
                ('clarification_description', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matching_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarification_call_bookings', to='matching.matchingattempt')),
            ],
            options={
                'verbose_name': 'Klärungsgespräch-Buchung',
                'verbose_name_plural': 'Klärungsgespräch-Buchungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
