# Generated by Django 6.0.2 on 2026-03-09 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0032_alter_requesttocoachtransition_from_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttocoachevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Zusätzliche strukturierte Informationen (z.B. Reminder-Typ, Deadline, etc.)'),
        ),
        migrations.AddField(
            model_name='requesttocoachevent',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, help_text='Benutzer, der das Ereignis ausgelöst hat (nur bei staff oder coach)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requesttocoachevent',
            name='event_type',
            field=models.CharField(choices=[('request_sent', 'Matching-Anfrage gesendet'), ('reminder_sent', 'Reminder gesendet'), ('accepted', 'Matching-Anfrage akzeptiert'), ('rejected', 'Matching-Anfrage abgelehnt'), ('timed_out', 'Deadline überschritten'), ('cancelled', 'Abgebrochen')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='requesttocoachevent',
            name='note',
            field=models.TextField(blank=True, help_text='Optionaler Kommentar zum Ereignis'),
        ),
        migrations.AddIndex(
            model_name='requesttocoachevent',
            index=models.Index(fields=['event_type'], name='matching_re_event_t_0ba8f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoachevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('triggered_by', 'system'), ('triggered_by_user__isnull', True)), models.Q(('triggered_by__in', ['staff', 'coach']), ('triggered_by_user__isnull', False)), _connector='OR'), name='rtc_event_valid_triggered_by_user'),
        ),
    ]
