# Generated by Django 6.0.2 on 2026-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0033_alter_matchingevent_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantactiontoken',
            name='action',
            field=models.CharField(choices=[('start_coaching', 'Coaching starten')], help_text='Baked in at creation — cannot change after the token is issued.', max_length=30, verbose_name='Aktion'),
        ),
    ]
