# Generated by Django 6.0.2 on 2026-04-19 07:00

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0034_alter_participantactiontoken_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattempt',
            name='state',
            field=django_fsm.FSMField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_rtc_reply', 'Warten auf Coach-Antwort zu Matching-Anfrage'), ('awaiting_intro_call_feedback_from_coach', 'Warten auf Coach-Antwort zu Intro-Call Anfrage'), ('awaiting_intro_call_feedback_from_participant', 'Warten auf TN-Antwort zu Intro-Call'), ('clarification_with_participant_needed', 'Klärung mit TN nötig'), ('clarification_call_scheduled', 'Klärungsgespräch gebucht'), ('matching_completed', 'Matching abgeschlossen'), ('failed', 'Keinen Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='in_preparation', max_length=50, protected=True),
        ),
    ]
