# Generated by Django 6.0.2 on 2026-03-09 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0035_alter_matchingattempt_status_and_more'),
        ('profiles', '0007_alter_coach_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchingattempt',
            name='unique_active_matching_attempt_per_participant',
        ),
        migrations.AddConstraint(
            model_name='matchingattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['in_preparation', 'ready_for_matching', 'matching_active', 'chemistry_pending'])), fields=('participant',), name='unique_active_matching_attempt_per_participant'),
        ),
    ]
