# Generated by Django 6.0.2 on 2026-03-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0036_remove_matchingattempt_unique_active_matching_attempt_per_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattempt',
            name='status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('chemistry_pending', 'Kennenlerngespräch läuft'), ('chemistry_timeout', 'Kennenlerngespräch nicht bestätigt'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='in_preparation', max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='from_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('chemistry_pending', 'Kennenlerngespräch läuft'), ('chemistry_timeout', 'Kennenlerngespräch nicht bestätigt'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='to_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('chemistry_pending', 'Kennenlerngespräch läuft'), ('chemistry_timeout', 'Kennenlerngespräch nicht bestätigt'), ('match_confirmed', 'Match bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
    ]
