# Generated by Django 6.0.2 on 2026-03-10 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0037_alter_matchingattempt_status_and_more'),
        ('profiles', '0007_alter_coach_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchingattempt',
            name='unique_active_matching_attempt_per_participant',
        ),
        migrations.AlterField(
            model_name='matchingattempt',
            name='status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('matching_confirmed', 'Matching bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='in_preparation', max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='from_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('matching_confirmed', 'Matching bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='to_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('matching_confirmed', 'Matching bestätigt'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='requesttocoachevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Matching-Anfrage erstellt'), ('request_sent', 'Matching-Anfrage gesendet'), ('reminder_sent', 'Reminder gesendet'), ('accepted', 'Matching-Anfrage akzeptiert'), ('rejected', 'Matching-Anfrage abgelehnt'), ('timed_out', 'Deadline überschritten'), ('cancelled', 'Abgebrochen')], db_index=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='matchingattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['in_preparation', 'ready_for_matching', 'matching_ongoing'])), fields=('participant',), name='unique_ongoing_matching_attempt_per_participant'),
        ),
    ]
