# Generated by Django 6.0.2 on 2026-03-10 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0038_remove_matchingattempt_unique_active_matching_attempt_per_participant_and_more'),
        ('profiles', '0007_alter_coach_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingattemptevent',
            name='actor',
        ),
        migrations.AddField(
            model_name='matchingattemptevent',
            name='triggered_by',
            field=models.CharField(choices=[('system', 'System'), ('staff', 'BL Mitarbeiter:in'), ('coach', 'Coach')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='matchingattemptevent',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, help_text='Benutzer, der das Ereignis ausgelöst hat (nur bei staff oder coach)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='matchingattemptevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('triggered_by', 'system'), ('triggered_by_user__isnull', True)), models.Q(('triggered_by__in', ['staff', 'coach']), ('triggered_by_user__isnull', False)), _connector='OR'), name='matching_attempt_event_valid_triggered_by_user'),
        ),
    ]
