# Generated by Django 6.0.2 on 2026-03-10 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0039_remove_matchingattemptevent_actor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchingattempttransition',
            name='matching_attempt_transition_actor_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='requesttocoachtransition',
            name='rtc_transition_valid_triggered_by_user',
        ),
        migrations.AddConstraint(
            model_name='matchingattempttransition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('triggered_by', 'system'), ('triggered_by_user__isnull', True)), models.Q(('triggered_by__in', ['staff', 'coach']), ('triggered_by_user__isnull', False)), _connector='OR'), name='matching_attempt_transition_triggered_by_consistency'),
        ),
        migrations.AddConstraint(
            model_name='requesttocoachtransition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('triggered_by', 'system'), ('triggered_by_user__isnull', True)), models.Q(('triggered_by__in', ['staff', 'coach']), ('triggered_by_user__isnull', False)), _connector='OR'), name='rtc_transition_valid_triggered_by_consistency'),
        ),
    ]
