# Generated by Django 6.0.2 on 2026-03-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0040_remove_matchingattempttransition_matching_attempt_transition_actor_consistency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='triggered_by',
            field=models.CharField(choices=[('system', 'System'), ('staff', 'BL Mitarbeiter:in'), ('coach', 'Coach')], default='system', max_length=20),
        ),
    ]
