# Generated by Django 6.0.2 on 2026-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0041_alter_matchingattempttransition_triggered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='triggered_by',
            field=models.CharField(choices=[('system', 'System'), ('staff', 'BL Mitarbeiter:in'), ('coach', 'Coach')], default='system', max_length=20),
        ),
    ]
