# Generated by Django 6.0.2 on 2026-03-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0042_alter_requesttocoachtransition_triggered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingattempt',
            name='automation_enabled_at',
        ),
    ]
