# Generated by Django 6.0.2 on 2026-03-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0043_remove_matchingattempt_automation_enabled_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchingattempttransition',
            name='matching_attempt_transition_triggered_by_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='requesttocoachtransition',
            name='rtc_transition_valid_triggered_by_consistency',
        ),
        migrations.RemoveField(
            model_name='matchingattempttransition',
            name='triggered_by',
        ),
        migrations.RemoveField(
            model_name='matchingattempttransition',
            name='triggered_by_user',
        ),
        migrations.RemoveField(
            model_name='requesttocoachtransition',
            name='triggered_by',
        ),
        migrations.RemoveField(
            model_name='requesttocoachtransition',
            name='triggered_by_user',
        ),
    ]
