# Generated by Django 6.0.2 on 2026-03-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0044_remove_matchingattempttransition_matching_attempt_transition_triggered_by_consistency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttocoach',
            name='status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_matching', 'Matching akzeptiert'), ('rejected_matching', 'Matching abgelehnt'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, default='in_preparation', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='from_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_matching', 'Matching akzeptiert'), ('rejected_matching', 'Matching abgelehnt'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='requesttocoachtransition',
            name='to_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('awaiting_reply', 'Warten auf Antwort'), ('accepted_matching', 'Matching akzeptiert'), ('rejected_matching', 'Matching abgelehnt'), ('no_response_until_deadline', 'Keine Rückmeldung'), ('cancelled', 'Anfrage abgebrochen')], db_index=True, max_length=50),
        ),
    ]
