# Generated by Django 6.0.2 on 2026-03-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0045_alter_requesttocoach_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchingattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Matching', 'verbose_name_plural': 'Matchings'},
        ),
        migrations.AlterModelOptions(
            name='matchingattemptevent',
            options={'ordering': ['created_at'], 'verbose_name': 'Matching-Ereignis', 'verbose_name_plural': 'Matching-Ereignisse'},
        ),
        migrations.AlterModelOptions(
            name='matchingattempttransition',
            options={'ordering': ['created_at'], 'verbose_name': 'Status Übergang Matching', 'verbose_name_plural': 'Status Übergänge Matchings'},
        ),
        migrations.AlterModelOptions(
            name='requesttocoachevent',
            options={'ordering': ['created_at'], 'verbose_name': 'Ereignis Matching-Anfrage', 'verbose_name_plural': 'Ereignisse Matching-Anfrage'},
        ),
        migrations.AlterModelOptions(
            name='requesttocoachtransition',
            options={'ordering': ['created_at'], 'verbose_name': 'Status Übergang Matching-Anfrage', 'verbose_name_plural': 'Status Übergänge Matching-Anfragen'},
        ),
    ]
