# Generated by Django 6.0.2 on 2026-03-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0046_alter_matchingattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttocoachtransition',
            options={'ordering': ['created_at'], 'verbose_name': 'Status Übergang einer Matching-Anfrage an Coach', 'verbose_name_plural': 'Status Übergänge der Matching-Anfragen an Coaches'},
        ),
    ]
