# Generated by Django 6.0.2 on 2026-03-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0047_alter_requesttocoachtransition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchingattemptevent',
            options={'ordering': ['created_at'], 'verbose_name': 'Ereignis Matching', 'verbose_name_plural': 'Ereignisse Matching'},
        ),
        migrations.AlterModelOptions(
            name='requesttocoachevent',
            options={'ordering': ['created_at'], 'verbose_name': 'Ereignis Matching-Anfrage an Coach', 'verbose_name_plural': 'Ereignisse Matching-Anfrage an Coaches'},
        ),
    ]
