# Generated by Django 6.0.2 on 2026-03-12 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0048_alter_matchingattemptevent_options_and_more'),
        ('profiles', '0007_alter_coach_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_attempts', to='profiles.participant', verbose_name='Teilnehmer:in'),
        ),
    ]
