# Generated by Django 6.0.2 on 2026-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0050_alter_matchingattempt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttocoach',
            name='ue',
            field=models.PositiveIntegerField(default=20, help_text='Anzahl der Unterrichtseinheiten, die der Coach übernehmen soll.', verbose_name='Unterrichtseinheiten'),
            preserve_default=False,
        ),
    ]
