# Generated by Django 6.0.2 on 2026-03-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0051_requesttocoach_ue'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingattempt',
            name='ue',
            field=models.PositiveIntegerField(default=48, help_text='Anzahl der genehmigten Unterrichtseinheiten.', verbose_name='Unterrichtseinheiten'),
            preserve_default=False,
        ),
    ]
