# Generated by Django 6.0.2 on 2026-03-14 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0052_matchingattempt_ue'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingattempt',
            name='background_information',
            field=models.TextField(default=django.utils.timezone.now, help_text='Zusätzliche Informationen zum Coaching, die für die Coaches relevant sein könnten.', verbose_name='Hintergrundinformationen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchingattempt',
            name='coaching_target',
            field=models.TextField(default='Bewerbungsunterlagen optimieren', help_text='Beschreibung des Coaching-Ziels.', verbose_name='Coaching-Ziel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchingattempt',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Datum und Uhrzeit des geplanten Coaching-Starts.', verbose_name='Geplanter Coaching-Start'),
            preserve_default=False,
        ),
    ]
