# Generated by Django 6.0.2 on 2026-03-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0053_matchingattempt_background_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingattempt',
            name='background_information',
        ),
        migrations.RemoveField(
            model_name='matchingattempt',
            name='coaching_target',
        ),
        migrations.RemoveField(
            model_name='matchingattempt',
            name='start_date',
        ),
    ]
