# Generated by Django 6.0.2 on 2026-03-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0055_alter_matchingattempt_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingattempt',
            name='chemistry_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='matchingattempt',
            name='chemistry_deadline_at',
        ),
        migrations.RemoveField(
            model_name='matchingattempt',
            name='chemistry_declined_at',
        ),
        migrations.RemoveField(
            model_name='matchingattempt',
            name='chemistry_requested_at',
        ),
    ]
