# Generated by Django 6.0.2 on 2026-03-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0056_remove_matchingattempt_chemistry_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingattempt',
            name='intro_call_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der Coach das Intro-Gespräch bestätigt hat.', null=True),
        ),
    ]
