# Generated by Django 6.0.2 on 2026-03-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0057_matchingattempt_intro_call_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingattempt',
            name='intro_call_requested_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der Coach erstmals gebenten wurde, einen Intro-Call mit dem(r) Teilnehmer:in zu organisieren.', null=True),
        ),
    ]
