# Generated by Django 6.0.2 on 2026-03-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0059_matchingattempt_intro_call_info_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattemptevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Matching erstellt'), ('started', 'Matching gestartet'), ('automation_enabled', 'Automatisierung aktiviert'), ('automation_disabled', 'Automatisierung deaktiviert'), ('automation_run', 'Automatisierung ausgeführt'), ('coach_request_sent', 'Coach-Anfrage versendet'), ('coach_accepted', 'Coach hat akzeptiert'), ('coach_declined', 'Coach hat abgelehnt'), ('coach_accepted_late', 'Coach hat verspätet akzeptiert'), ('coach_declined_late', 'Coach hat verspätet abgelehnt'), ('coach_response_ignored', 'Coach-Antwort ignoriert'), ('request_deadline_passed', 'Antwortfrist des Coaches abgelaufen'), ('intro_call_requested', 'Intro-Call angefragt'), ('intro_call_confirmed', 'Intro-Call bestätigt'), ('intro_call_declined', 'Intro-Call abgelehnt'), ('intro_call_info_sent', 'Intro-Call Info versendet'), ('intro_confirmation_deadline_passed', 'Frist zur Bestätigung des Intro-Calls abgelaufen'), ('intro_call_timeout', 'Intro-Call-Frist überschritten'), ('reminder_sent', 'Erinnerung versendet'), ('manual_override', 'Manuelle Entscheidung durch Mitarbeiter'), ('staff_cancelled_requests', 'Coach-Anfragen durch Mitarbeiter abgebrochen')], max_length=64),
        ),
    ]
