# Generated by Django 6.0.2 on 2026-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0060_alter_matchingattemptevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachactiontoken',
            name='action',
            field=models.CharField(choices=[('accept', 'Annehmen'), ('decline', 'Ablehnen'), ('confirm_intro_call', 'Intro-Call bestätigen')], help_text='Baked in at creation — cannot change after the token is issued.', max_length=18, verbose_name='Aktion'),
        ),
    ]
