# Generated by Django 6.0.2 on 2026-03-16 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0061_alter_coachactiontoken_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachactiontoken',
            name='matching_attempt',
            field=models.ForeignKey(blank=True, help_text='Das Matching, auf das sich dieser Token bezieht.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_action_tokens', to='matching.matchingattempt', verbose_name='Matching'),
        ),
        migrations.AlterField(
            model_name='coachactiontoken',
            name='request_to_coach',
            field=models.ForeignKey(blank=True, help_text='Die Coach-Anfrage, auf die sich dieser Token bezieht.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_tokens', to='matching.requesttocoach', verbose_name='Anfrage an Coach'),
        ),
        migrations.AddConstraint(
            model_name='coachactiontoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('request_to_coach__isnull', False), ('matching_attempt__isnull', True)), models.Q(('request_to_coach__isnull', True), ('matching_attempt__isnull', False)), _connector='OR'), name='coach_action_token_linked_to_either_request_or_attempt'),
        ),
    ]
