# Generated by Django 6.0.2 on 2026-03-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0063_alter_matchingattempt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingattempt',
            name='status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('matching_confirmed', 'Matching bestätigt'), ('ready_for_intro_call', 'Bereit für Intro-Call'), ('awaiting_intro_call_feedback', 'Warten auf Intro-Call Rückmeldung'), ('ready_for_start_email', 'Bereit für Start-E-Mail'), ('matching_completed', 'Matching abgeschlossen'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], db_index=True, default='in_preparation', max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='from_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('matching_confirmed', 'Matching bestätigt'), ('ready_for_intro_call', 'Bereit für Intro-Call'), ('awaiting_intro_call_feedback', 'Warten auf Intro-Call Rückmeldung'), ('ready_for_start_email', 'Bereit für Start-E-Mail'), ('matching_completed', 'Matching abgeschlossen'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matchingattempttransition',
            name='to_status',
            field=models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('ready_for_matching', 'Bereit für Matching'), ('matching_ongoing', 'Matching läuft'), ('matching_confirmed', 'Matching bestätigt'), ('ready_for_intro_call', 'Bereit für Intro-Call'), ('awaiting_intro_call_feedback', 'Warten auf Intro-Call Rückmeldung'), ('ready_for_start_email', 'Bereit für Start-E-Mail'), ('matching_completed', 'Matching abgeschlossen'), ('failed', 'Kein Coach gefunden'), ('cancelled', 'Matching abgebrochen')], max_length=50),
        ),
    ]
