# Generated by Django 6.0.2 on 2026-03-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0065_alter_matchingattempt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingattempt',
            name='coaching_start_info_sent_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der/die Teilnehmer:in und der Coach eine Info zum Start des Coachings erhalten haben.', null=True),
        ),
        migrations.AlterField(
            model_name='matchingattempt',
            name='intro_call_info_sent_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der/die Teilnehmer:in und der Coach Infos für ein Kennenlerngespräch (Intro-Call) erhalten haben.', null=True),
        ),
        migrations.AlterField(
            model_name='matchingattempt',
            name='intro_call_requested_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem der Coach erstmals gebeten wurde, einen Intro-Call mit dem(r) Teilnehmer:in zu organisieren.', null=True),
        ),
        migrations.AlterField(
            model_name='matchingattemptevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Matching erstellt'), ('started', 'Matching gestartet'), ('automation_enabled', 'Automatisierung aktiviert'), ('automation_disabled', 'Automatisierung deaktiviert'), ('automation_run', 'Automatisierung ausgeführt'), ('coach_request_sent', 'Coach-Anfrage versendet'), ('coach_accepted', 'Coach hat akzeptiert'), ('coach_declined', 'Coach hat abgelehnt'), ('coach_accepted_late', 'Coach hat verspätet akzeptiert'), ('coach_declined_late', 'Coach hat verspätet abgelehnt'), ('coach_response_ignored', 'Coach-Antwort ignoriert'), ('request_deadline_passed', 'Antwortfrist des Coaches abgelaufen'), ('intro_call_requested', 'Intro-Call angefragt'), ('intro_call_confirmed', 'Intro-Call bestätigt'), ('intro_call_declined', 'Intro-Call abgelehnt'), ('intro_call_info_sent', 'Intro-Call Info versendet'), ('coaching_start_info_sent', 'Coaching-Start Info versendet'), ('intro_confirmation_deadline_passed', 'Frist zur Bestätigung des Intro-Calls abgelaufen'), ('intro_call_timeout', 'Intro-Call-Frist überschritten'), ('reminder_sent', 'Erinnerung versendet'), ('manual_override', 'Manuelle Entscheidung durch Mitarbeiter'), ('staff_cancelled_requests', 'Coach-Anfragen durch Mitarbeiter abgebrochen')], max_length=64),
        ),
    ]
