# Generated by Django 6.0.2 on 2026-03-29 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendly_event_uri', models.URLField(max_length=500, unique=True)),
                ('calendly_invitee_uri', models.URLField(max_length=500, unique=True)),
                ('calendly_event_uuid', models.CharField(blank=True, max_length=100)),
                ('invitee_first_name', models.CharField(blank=True, max_length=255)),
                ('invitee_last_name', models.CharField(blank=True, max_length=255)),
                ('invitee_name', models.CharField(blank=True, max_length=255)),
                ('invitee_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('event_name', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=50)),
                ('questions_and_answers', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
