# Generated by Django 6.0.2 on 2026-03-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlybooking',
            name='calendly_event_uri',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
