# Generated by Django 6.0.2 on 2026-05-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendlybooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Calendly Erstgespräch', 'verbose_name_plural': 'Calendly Erstgespräche'},
        ),
    ]
