# Generated by Django 6.0.2 on 2026-03-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_calendlybooking_calendly_event_uri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendlybooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Calendly Buchung', 'verbose_name_plural': 'Calendly Buchungen'},
        ),
    ]
