# Generated by Django 6.0.2 on 2026-04-04 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_calendlybooking_options'),
        ('profiles', '0005_coach_website_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTalk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('invitee_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('talk_date', models.DateTimeField(blank=True, null=True, verbose_name='Gesprächsdatum')),
                ('outcome', models.CharField(choices=[('proceed', 'Proceed'), ('not_proceed', 'Not proceed'), ('undecided', 'Undecided')], db_index=True, default='undecided', max_length=20, verbose_name='Ergebnis')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen / Zusammenfassung')),
                ('coaching_goal', models.TextField(blank=True, verbose_name='Coaching-Ziel')),
                ('background', models.TextField(blank=True, verbose_name='Hintergrund')),
                ('follow_up_actions', models.TextField(blank=True, verbose_name='Nächste Schritte')),
                ('avgs_available', models.BooleanField(blank=True, null=True, verbose_name='AVGS-Gutschein vorhanden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendly_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_talk', to='bookings.calendlybooking', verbose_name='Calendly-Buchung')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_talks', to='profiles.beginnerluftstaff', verbose_name='Durchgeführt von')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_talks', to='profiles.participant', verbose_name='Teilnehmer:in')),
            ],
            options={
                'verbose_name': 'Erstgespräch',
                'verbose_name_plural': 'Erstgespräche',
                'ordering': ['-talk_date', '-created_at'],
            },
        ),
    ]
