# Generated by Django 6.0.2 on 2026-04-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_first_talk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstTalk',
        ),
    ]
